### ISSUE TITLE
Decrease descriptor dimension

### ISSUE THREAD

**Issue by roborocklsm** [rpautrat/SuperPoint#101]
I am going to decrease the dimension of the descriptor (from 256 to 128). Since the ouput size is too large and 1/3 of the inference time is doing memory moving from GPU to CPU (called MemoryDtoH). Have you ever tried this before?

**Comment by rpautrat** [comment]
No, but I am curious to know if it has a significant on the performance or not. Let me know if you get an evaluation of the reduced descriptor so that we can compare it to the current version!

**Comment by roborocklsm** [comment]
Sure. If there would be any inference time improvement, I guess it is only for embedded device. Since MemoryDtoH is not a significant delay on PC.

**Comment by rpautrat** [comment]
@roborocklsm, what was the outcome of your test to reduce the size of the descriptor in the end? Did you observe a loss of performance? Did it improve again the speed of inference (at least on embedded devices)?

**Comment by roborocklsm** [comment]
@rpautrat 

Generally, the keypoint detection is good (SLAM-ready) but the descriptors are not (the number of matching pairs are small ). 

I reduce the size of superpoint, and now it goes around 10fps on Jetson Nano after speeding up by TensorRT, meanwhile ORB could go to 50 fps easily. 

According to the characters of SuperPoint,  it needs to compute descriptors for every single pixel in the input image (e.g. if the input size is 480*640 and we need 500 keypoints per image, superpoint needs to calculate 307200 descriptors and then filer them to 500, but ORB only need to compute 500 descriptors).

There is something wrong with my network, i cannot upload the comparison results between my tiny version of SuperPoint and ORB.

To be honest, I did not reproduce a good version of SuperPoint to beat ORB on embedded devices.

**Comment by rpautrat** [comment]
I see, thanks for sharing your results.
Yes it is the problem with dense descriptors: in the end we only use a very small part of all the descriptors computed...
