### ISSUE TITLE
About detector_evaluation_magic_point

### ISSUE THREAD

**Issue by yanhuanhuanyy** [rpautrat/SuperPoint#102]
Hi, @rpautrat. When I run the notebooks of detector_evaluation_magic_point.ipynb, I have some doubts about the results. 
![TIM图片20190826155107](https://user-images.githubusercontent.com/36001989/63674607-7a1d7800-c819-11e9-871d-bb5f623c834f.png)
![下载](https://user-images.githubusercontent.com/36001989/63674610-7be73b80-c819-11e9-8a09-371e7e1c020d.png)
'mp_synth-v6_noph-aug_synth-noise' and 'mp_synth-v6_photo-aug_synth-noise'  are different from yours. When I do the 'mp_synth-v6_noph-aug_synth-noise' experiment, I set data->photometric->enable = false and add_augmentation_to_test_set = true. The 'mp_synth-v6_photo-aug_synth-noise' experiment, the parameter data->photometric->enable was true and add_augmentation_to_test_set = true. I use the command python export_detections.py configs/magic-point_shapes.yaml magic-point_synth --export_name=mp_synth-v6_noph-aug_synth-noise.
Could you give me some advice?

**Comment by rpautrat** [comment]
The commands you ran seem to be correct. So I think that the differences you observed are only due to the fact that we trained a slightly different model. It is however indeed weird that we get such discrepancies when applying noise.
I wouldn't worry too much about it though, since the complete model 'mp_synth-v6_photo-aug_synth' is still showing a good performance and is beating the others.

**Comment by yanhuanhuanyy** [comment]
Okay, thank you again for your kindness!

**Comment by cumtchenchang** [comment]
@yanhuanhuanyy  Hi, I want to know how to generate mp_synth-v6_noph-aug_synth-noise, mp_synth-v6_photo-aug_synth-noise and so on. I did not find how to generate followed  Readme. Thank you

**Comment by yanhuanhuanyy** [comment]
1. for mp_synth-v6_noph-aug_synth-noise :
first, change data->photometric->enable = false and add_augmentation_to_test_set = true **in magic-point_shapes.yaml**, then use the command: python export_detections.py configs/magic-point_shapes.yaml magic-point_synth --export_name=mp_synth-v6_noph-aug_synth-noise.
2.The difference between 'mp_synth-v6_noph-aug_synth-noise' and 'mp_synth-v6_noph-aug_synth' is that the 'add_augmentation_to_test_set'  parameters of the former is true and the latter is false. (set to true to evaluate with noise). 
3.The difference between 'mp_synth-v6_noph-aug_synth' and 'mp_synth-v6_photo-aug_synth' is that the 'data->photometric->enable' parameters of the former is false and the latter is true. 
The relevant issue is #32 . Each experiment remembers to modify the parameters of the magic-point_shapes.yaml file and 'export_name' in the command line.

**Comment by cumtchenchang** [comment]
@yanhuanhuanyy @rpautrat  Thank you for your help. In this code, harris, shi, and fast are used to evaluate the mAP, but mAP is used to evaluate descriptors and harris, shi, and fast are not used as descriptors in researches.  In the original paper, SIFT and ORB are used to evaluate Rep. MLE,  NN mAP, and M. Score.

**Comment by rpautrat** [comment]
The mAP used in this script is the corner detection Average Precision and is a detector metric (described in the original article), not the NN mAP.

**Comment by cumtchenchang** [comment]
@Thank you for your response. That is to say, nearest neighbor mAP and matching score are evaluated in your code?

**Comment by rpautrat** [comment]
I already told you that it was not the case in https://github.com/rpautrat/SuperPoint/issues/103#issuecomment-525489664

**Comment by cumtchenchang** [comment]
Sorry, I got it.

**Comment by yanhuanhuanyy** [comment]
@cumtchenchang , I'm sorry. It was all my fault. About 'mp_synth-v6_noph-aug_synth-noise' experiment, the relevant issue is #12 , not ''#32'', I've modified it. Maybe you can read the 'SuperPoint: Self-Supervised Interest Point Detection and Description' article(https://arxiv.org/pdf/1712.07629.pdf), which will help you understand the code implementation.

**Comment by cumtchenchang** [comment]
@yanhuanhuanyy  Thank you. could you connect you with WeChat?  my number is +86 1820 520 5900.
