### ISSUE TITLE
Obtaining Detection Sizes

### ISSUE THREAD

**Issue by half-potato** [rpautrat/SuperPoint#105]
Is there a way I can estimate the size of the patch around the descriptor detected? I would like to include SuperPoint in a test but I need a size for some rectangular region surrounding a point detected. I was thinking of using the interest map to estimate the size of the detection using the size of the derivative at the detection point. Would this work?

**Comment by rpautrat** [comment]
Hi!

SuperPoint is by definition not a patch descriptors, so there is no proper size of the detection.

I don't think that using the gradient of the interest map would work, as you would probably get very small patch sizes.

What you could possibly do is to compute the gradient of the descriptor you are looking at, relative to all of the original pixels in the image. Then you can threshold to keep only the highest gradients and see what were the most relevant pixels in the original image. But it won't be a squared patch, so you would need to fit a square to these relevant pixels.

The best way to evaluate SuperPoint with other descriptors is to use full images, extract all the features and then you can compare patch descriptors with SuperPoint descriptors.

**Comment by half-potato** [comment]
Thanks! That sounds like an interesting approach. The reason I ask is because I am trying to evaluate the repeatability of SuperPoint detections. If I want to check if a detection has been detected reliably across two viewpoints, I need to be able to project the detection into 3D space and check if it's detected again. 

My question is whether it would be fair to expect SuperPoint is reliably detect the same exact point in 3D space or if it would be more reasonable for it to detect a 3x3 region around that point.

**Comment by rpautrat** [comment]
The evaluation of repeatability is available in this repo (have a look at `evaluations/detector_evaluation.py` and the notebook `detector_repeatability_coco.py`). You can modify there the distance to consider a match between two points as acceptable. But typically, we indeed use a window of 3x3 to define repeatability.
