### ISSUE TITLE
MagicPoint live test

### ISSUE THREAD

**Issue by GhaCH** [rpautrat/SuperPoint#107]
Hi !
I trained magicPoint with my own dataset and I wonder if it could be tested in real time with a camera.
Where should I make changes if I want to use export_detections.py?

**Comment by rpautrat** [comment]
Hi!
You can first export the model you trained with the following code: https://github.com/mmmfarrell/SuperPoint/blob/master/superpoint/export_model.py and then use it to run MagicPoint in real time. For that, you can take inspiration of this code: https://github.com/mmmfarrell/SuperPoint/blob/master/superpoint/match_features_demo.py

**Comment by GhaCH** [comment]
Thanks for the tip.
I have another question.
In match_features_demo.py, I need to change these lines so I can run it with MagicPoint: https://github.com/mmmfarrell/SuperPoint/blob/2e6c1d8f3ea630611bbd8922197e9ab27e6aa160/superpoint/match_features_demo.py#L117-L119
How am I supposed to do that?

**Comment by rpautrat** [comment]
Using the following code should work:
```
input_img_tensor = graph.get_tensor_by_name('magicpoint/image:0')
output_prob_nms_tensor = graph.get_tensor_by_name('magicpoint/prob_nms:0')
```
