### ISSUE TITLE
Superpoint feature matching 

### ISSUE THREAD

**Issue by VPRzhou** [rpautrat/SuperPoint#112]
Hi,can you show me a demo about the Superpoint feature match.For I want compare it with other features and demonstrate the roboutness of Superpoint in varying conditions.
Looking forward your reply,thank you.

**Comment by rpautrat** [comment]
Hi,
You can find a demo here: https://github.com/mmmfarrell/SuperPoint
You can also check the notebooks for an evaluation of SuperPoint with other detectors/descriptors: https://github.com/rpautrat/SuperPoint/blob/master/notebooks/detector_repeatability_hpatches.ipynb and https://github.com/rpautrat/SuperPoint/blob/master/notebooks/descriptors_evaluation_on_hpatches.ipynb

**Comment by b51** [comment]
You can check a demo here, https://github.com/b51/FeatureTracker, a comparison between ORB and SuperPoint, use https://github.com/MagicLeapResearch/SuperPointPretrainedNetwork pretrained model
