### ISSUE TITLE
magic_point model for our own dataset

### ISSUE THREAD

**Issue by yanhuanhuanyy** [rpautrat/SuperPoint#113]
Hi, @rpautrat . I want to train a magic_point model for our own dataset. 
Synthetic shapes dataset has 10 categories, including  rendered triangles, quadrilaterals, lines, cubes, checkerboards, and stars each with ground truth corner locations. I want to delete cubes and checkerboards, but I don't know how to do. modifing the magic-point_shapes.yaml file ? How do I modify it?
Thanks very much and I am looking forward to your reply.

**Comment by thomasstats** [comment]
In synthetic_shapes.py there's a variable called drawing_primitives.  It's a list of shapes to generate.  Remove whichever shapes from there that you don't want drawn.

**Comment by rpautrat** [comment]
Or better, in the line in `configs/magic-point_shapes.yaml`:

```
primitives: 'all'
```

Replace 'all' by the list of shapes that you want to use, from this list:

```
[ 'draw_lines',  'draw_polygon',  'draw_multiple_polygons',  'draw_ellipses',  'draw_star',  'draw_checkerboard', 'draw_stripes',  'draw_cube',  'gaussian_noise']
```

**Comment by yanhuanhuanyy** [comment]
@thomasstats and @rpautrat , I am deeply grateful for your help. It works~
