### ISSUE TITLE
Hpatches evaluation steps

### ISSUE THREAD

**Issue by cumtchenchang** [rpautrat/SuperPoint#115]
Hi, I am sorry to disturb you again. When changing the correctness, features and descriptors need to be re-extracted each time. Why not change the code first to extract features and descriptors. Then use different correctness on them. If so, more operations can be performed on the same generated data, such as the ratio test, too_key_points, RANSAC. Thank you.

**Comment by rpautrat** [comment]
Hi,

I am not sure to understand you. The features and descriptors need only to be extracted once currently. And you can change the correctness threshold directly in the evaluation code https://github.com/rpautrat/SuperPoint/blob/2962dde0687b36779291ea565c334487a89ce7fe/superpoint/evaluations/descriptor_evaluation.py#L54

So what is the problem exactly?

**Comment by cumtchenchang** [comment]
Thank you for your response, when using evaluation of the descriptors with homography estimation on HPatches:
python export_descriptors.py configs/superpoint_hpatches.yaml superpoint_coco --export_name=superpoint_hpatches-v
correctness threshold is fixed and  .npz files will be generated. If you change the threshold, new files will be generated too. When changing the threshold from 0 to 10, there will be very repetitive operations and the time will be very long. If adding other metrics, such as MMA, these steps will take more time.
![image](https://user-images.githubusercontent.com/24315713/67912746-da3bec00-fbc5-11e9-8a05-6feceeac9dad.png)

**Comment by rpautrat** [comment]
t is indeed the correctness threshold.

But the points predicted by SuperPoint (e.g. points (x1, y1) and (x2, y2)) are always the same, whatever t is. The only thing that changes with t is if point (x1, y1) is matched with point (x2, y2) or not.

So in your equation H, (x1, y1) and (x2, y2) are constant and if t changes, only #correct matches and MMA will change. No need to recompute (x1, y1) and (x2, y2).
