### ISSUE TITLE
About Synthetic shapes?

### ISSUE THREAD

**Issue by xlong0513** [rpautrat/SuperPoint#118]
Hi. Not an issue here, but a question. 
When training the MagicPoint, how are the synthetic datasets created? 
I mean, i don't see the creation process of the  synthetic datasets.
Sorry for my poor Python skill.

**Comment by rpautrat** [comment]
Hi,
The synthetic dataset is created with OpenCV, here: https://github.com/rpautrat/SuperPoint/blob/master/superpoint/datasets/synthetic_dataset.py

**Comment by xlong0513** [comment]
Thank u.
I didn't make it clear. I mean in which function is the creation process called? Is it the "_init_graph" in "experiment.py". 
And how can i visualize the synthetic shapes?

**Comment by rpautrat** [comment]
Yes, __init_graph_ will initialize the dataset and if it is the first time you use it, it will export all the synthetic shapes on disk.

There is a notebook to visualize the synthetic shapes: https://github.com/rpautrat/SuperPoint/blob/master/notebooks/visualize_synthetic-shapes.ipynb

**Comment by xlong0513** [comment]
I see. Thank u for the quick reply !!!

**Comment by xlong0513** [comment]
Hi, sorry to bother again.
I got this omp error when training MagicPoint with Synthetic Shapes.
![图片](https://user-images.githubusercontent.com/35829321/68593586-c26f3c80-04d0-11ea-898b-7dc99ff93ac4.png)
It seems OpenMP is lost. Thank u for the attention.

**Comment by xlong0513** [comment]
I fix it with the following command
`conda install mkl-rt`
Thanks.

**Comment by rpautrat** [comment]
Thanks for sharing the fix!

**Comment by saraswathi421** [comment]
Hi, 
Are there any labels generating from the draw_ellipses function? All other shapes are returning points, but this function is returning an empty numpy array.

**Comment by rpautrat** [comment]
Hi,
MagicPoint is a corner detector and there are no corners on an ellipse, so no labels for ellipses. You can see these ellipses as distractors if you want.

**Comment by saraswathi421** [comment]
Thank you for your quick response,
I have one more question, just like how we are repeating magic point 2 or 3 times, is it recommended to repeat superpoint as well ?

**Comment by rpautrat** [comment]
No, it shouldn't be necessary to repeat SuperPoint. Repeating MagicPoint is useful to improve the ground truth points, but once they are good enough, SuperPoint can reuse them in a single training.

**Comment by gx0522** [comment]
Hi,
I don't know how to create the synthetic datasets because of my pool python 。 Could you please share the dataset in github。
Thanks

**Comment by paragghosh** [comment]
@rpautrat , I am getting a strange error while trying to train MagicPoint on Synthetic Shapes:  
![image](https://user-images.githubusercontent.com/29264978/128126501-e4211d20-395d-421c-aa72-66299b33ef65.png)
Any clue would help immensely.

**Comment by rpautrat** [comment]
Hi, there is already an issue related to that topic: https://github.com/rpautrat/SuperPoint/issues/29
It can be caused either with an incompatible TF version, or if the wrong channel ordering is specified. I would recommend using versions 1.12<=TF<=1.14, instead of the 1.6 / 1.7 suggested in the old issue.

**Comment by rpautrat** [comment]
The config file looks fine. Maybe you can instead try the configuration suggested in https://github.com/rpautrat/SuperPoint/issues/173, it has been proved to work for many people already.
