### ISSUE TITLE
try to slim base  network

### ISSUE THREAD

**Issue by akkaze** [rpautrat/SuperPoint#119]
I am now trying to slim the network for low latency.however,with the decreasing of params,the network converges to bad result.I'm wondering have  anyone succeded in shriking the model size

**Comment by Vincentqyw** [comment]
> I am now trying to slim the network for low latency.however,with the decreasing of params,the network converges to bad result.I'm wondering have anyone succeded in shriking the model size

You can re-train the model using the encoder of MagicPointS with params `9-9-16-16-32-32-32-32-32`.

**Comment by rpautrat** [comment]
@akkaze, did you get more satisfactory results with the architecture proposed by @Vincentqyw?
