### ISSUE TITLE
Cholesky decomposition error

### ISSUE THREAD

**Issue by ucmmesa** [rpautrat/SuperPoint#12]
when I try to use the cmd "python experiment.py train configs/magic-point_shapes.yaml magic-point_synth" on my gtx1070 gpu,Iter 0 is executed.But,and then no less than 1000 iterations,error prompt pops up and says the Cholesky decomposition was not successful.I don't know why and I wonder if the code can run on a GTX1070 GPU.Can you give me any suggestions?

**Comment by rpautrat** [comment]
Someone reported me a similar error. Apparently the Cholesky decomposition can fail in tf.matrix_solve_ls(a_mat, p_mat, fast=True) (line 217 of superpoint/models/homographies.py). Setting fast=False resolved this issue. I hope it can solve your problem.

However this bug only appeared when training on the synthetic shapes, so you might be able to use fast=True when training on the COCO dataset.

**Comment by ucmmesa** [comment]
Yes,setting fast=False works.Thanks.
But,when executing the script of "python export_detections.py configs/magic-point_coco_export.yaml magic-point_synth --pred_only --batch_size=5 --export_name=magic-point_coco-export1",another error occurred:
InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'magicpoint/pred_tower0/while/MatrixSolveLs': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]

	 [[Node: magicpoint/pred_tower0/while/MatrixSolveLs = MatrixSolveLs[T=DT_FLOAT, fast=false, _device="/device:GPU:0"](magicpoint/pred_tower0/while/stack_4, magicpoint/pred_tower0/while/transpose, magicpoint/pred_tower0/while/MatrixSolveLs/l2_regularizer)]]

What's wrong?

**Comment by rpautrat** [comment]
No GPU device has been found on your machine apparently. Are you sure that you ran the code with a machine supporting GPU usage?

If this error only appears with MatrixSolveLs, you can also try to set back false=True in tf.matrix_solve_ls(a_mat, p_mat, fast=True), to run the code on the COCO dataset. The person that had experienced a similar issue to yours had to do that when switching to COCO.

**Comment by ucmmesa** [comment]
I first train MagicPoint on Synthetic Shapes with gpu ,using the command of " python experiment.py train configs/magic-point_shapes.yaml magic-point_synth",and then try to export detections on MS-COCO,using "python export_detections.py configs/magic-point_coco_export.yaml magic-point_synth --pred_only --batch_size=5 --export_name=magic-point_coco-export1".Should I use the model trained on dataset COCO to export detections on COCO?

**Comment by ucmmesa** [comment]
Another question:if I want to do the experiments in the list of:
 experiments = [
    'mp_synth-v6_no-aug_synth', 'mp_synth-v6_no-aug_synth-noise',
    'mp_synth-v6_photo-aug_synth', 'mp_synth-v6_photo-aug_synth-noise',
    'harris_synth-v6', 'harris_synth-v6-noise',
    'shi_synth-v6', 'shi_synth-v6-noise',
    'fast_synth-v6', 'fast_synth-v6-noise',
]
,as shown in detector_evaluation_magic_point.ipynb,which yaml should be used respectively?

**Comment by rpautrat** [comment]
No, you did it the right way (first train MagicPoint on the synthetic shapes, and then export the detections on COCO with the previous model).
You changed fast=False to train the model, but can you try to set it back to fast=True when doing the export on COCO? It might solve your new issue.

**Comment by rpautrat** [comment]
To do the experiments = [
'mp_synth-v6_no-aug_synth', 'mp_synth-v6_no-aug_synth-noise',
'mp_synth-v6_photo-aug_synth', 'mp_synth-v6_photo-aug_synth-noise',
'harris_synth-v6', 'harris_synth-v6-noise',
'shi_synth-v6', 'shi_synth-v6-noise',
'fast_synth-v6', 'fast_synth-v6-noise',
],
you need to use the command `python experiment.py evaluate configs/<yaml_file> magic-point_synth`. The yaml file should be `magic-point_shapes.yaml` for the experiments starting with mp_synth-v6_* and `classical-detectors_shapes.yaml` for the other experiments (you can choose the classical detector you want in the field model->method). To evaluate with noise, you need to set the field data->add_augmentation_to_test_set to True.

The difference between 'mp_synth-v6_no-aug_synth' and 'mp_synth-v6_photo-aug_synth' is that the first one is trained without photometric augmentation (field data->photometric->enable = false) whereas the second has photometric augmentations.

**Comment by ucmmesa** [comment]
Thanks.I'll try it.
After the third step in usage,"python experiment.py train configs/magic-point_coco_train.yaml magic-point_coco",is the model got in the magic-point_coco directory so called superpoint detector model?

**Comment by rpautrat** [comment]
Yes, exactly. Actually, once you have this model 'magic-point_coco', you can repeat the steps 2 and 3 (export new labels on the COCO dataset with homographic adaptation and train the model with them) several time to improve the model (according to the paper, the original authors followed the steps 2 and 3 twice). But in the end you get the superpoint detector model.

**Comment by ucmmesa** [comment]
In detector_evaluation_magic_point.ipynb, and the experiments = [
'mp_synth-v6_no-aug_synth', 'mp_synth-v6_no-aug_synth-noise',
'mp_synth-v6_photo-aug_synth', 'mp_synth-v6_photo-aug_synth-noise',
'harris_synth-v6', 'harris_synth-v6-noise',
'shi_synth-v6', 'shi_synth-v6-noise',
'fast_synth-v6', 'fast_synth-v6-noise',
],
if command python experiment.py evaluate configs/classical-detectors_shapes.yaml harris_synth_v6 is executed,the result should be eval.txt in the directory of harris_synth_v6,right?
If so, "KeyError: 'prob is not a file in the archive'" occurred.

Furthermore,in visualize_coco_adaptation-iterations.ipynb,what do the experiments in the list of  exp = [
    'mp_synth-v6_photo-hom-aug_hp-v-repeat',
    'mp_synth-v6_photo-hom-aug_ha2-100-0_hp-v-repeat',
    'harris_hp-v-repeat',
] mean?

**Comment by rpautrat** [comment]
Oops, sorry, I made a mistake: it is not `experiment.py evaluate` that you need to use to generate the experiments, but rather `python export_detections.py configs/<yaml_file> magic-point_synth`.
The parameter "eval_iter" allows you to choose the number of images that will be used. This command should create the folder with the results of the experiment in your $EXPERIMENT_PATH/outputs/.

As for your second question:
'mp_synth-v6_photo-hom-aug_hp-v-repeat' -> evaluation of the repeatability of magicpoint trained with photometric and homographic augmentation on HPatches viewpoint (hp-v).
'mp_synth-v6_photo-hom-aug_ha2-100-0_hp-v-repeat' -> same, but with: one training of MagicPoint on COCO, one homographic adaptation to refine the labels, another training on COCO with the new labels and finally another homographic adaptation for the final prediction (ha2 means 2 homographic adaptations).
'harris_hp-v-repeat' -> repeatability of Harris corner detector on HPatches viewpoint.

All these experiments are computed using `export_detections_repeatability.py` (the two first with the yaml file `configs/magic-point_repeatability.yaml` and the third one with `configs/classical-detectors_repeatability.yaml`)

**Comment by rpautrat** [comment]
There is no possibility to retrain a model from a previous checkpoint (for now), so when you do that, the training starts from scratch, hence the zero precision and recall at the beginning.

**Comment by ucmmesa** [comment]
No,I can't tackle it.


________________________________
发件人: xz1cv <notifications@github.com>
发送时间: 2018年9月4日 6:24
收件人: rpautrat/SuperPoint
抄送: ucmmesa; Mention
主题: Re: [rpautrat/SuperPoint] Cholesky decomposition error (#12)


@ucmmesa<https://github.com/ucmmesa> I also find the precision and recall do not change in the training process using synthetic data, have you figure it out?

―

**Comment by rpautrat** [comment]
Sorry for the delay.
@ucmmesa As there is a duplicate issue (https://github.com/rpautrat/SuperPoint/issues/15), I suggest to close this one and continue with the issue of @xz1cv.

**Comment by siyuada** [comment]
@ucmmesa Hey, have you solved the problem?
I get the same Cholesky error when I want to export detector on COCO dataset.
And I set the fast = False, then it happens:
```
InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'magicpoint/pred_tower0/while/MatrixSolveLs': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]

         [[Node: magicpoint/pred_tower0/while/MatrixSolveLs = MatrixSolveLs[T=DT_FLOAT, fast=false, _device="/device:GPU:0"](magicpoint/pred_tower0/while/stack_4, magicpoint/pred_tower0/while/transpose, magicpoint/pred_tower0/while/MatrixSolveLs/l2_regularizer)]]
```
I am sure I run this code in GPU(RTX2080), it is like that some operations don't support GPU?

**Comment by rpautrat** [comment]
@siyuada, did you try to export on COCO with fast = True? Because one person that had this issue had to use False when using the synthetic dataset and True when using COCO (for some unknown reason...).

**Comment by siyuada** [comment]
@rpautrat, Thanks for your reply.
I train on synthetic dataset with fast = True, it has no error.
Then I want to export on COCO with that model. If I do that with ```fast = True```, it has some error: ```OP_REQUIRES failed at cholesky_op.cc```
![image](https://user-images.githubusercontent.com/34361090/56883781-46645880-6a9a-11e9-92c6-b1eb78c30b28.png)

So I find this issues, hope to get some help. I tried to export on COCO with ```fast=False```, however, it still some problems like @ucmmesa faced.

![image](https://user-images.githubusercontent.com/34361090/56883967-dc987e80-6a9a-11e9-8694-8a30e1c35e15.png)

It seems like this operation can not run on GPU?

**Comment by rpautrat** [comment]
This is a weird error indeed. Can you try to replace line 217 of `superpoint/models/homographies.py` by:
```
with tf.device('/cpu:0'):
  homography = tf.transpose(tf.matrix_solve_ls(a_mat, p_mat, fast=False))
```
It should force it to use the CPU instead of the GPU.

**Comment by roborocklsm** [comment]
@siyuada hey, did you solve this problem at last? Since I met the same problem as you do.

I would be appreciated if you could share your solution.

**Comment by roborocklsm** [comment]
I guess it is using gpu to do NMS work, which may not supported by gpu operations.
```
InternalError (see above for traceback): tensorflow/core/kernels/cuda_solvers.cc:375: cuSolverDN call failed with status =7
	 [[Node: magicpoint/pred_tower0/while/matrix_solve_ls/Cholesky = Cholesky[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](magicpoint/pred_tower0/while/matrix_solve_ls/MatMul)]]
	 [[Node: magicpoint/pred_tower0/map/while/box_nms/GatherNd/_149 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_998_magicpoint/pred_tower0/map/while/box_nms/GatherNd", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopmagicpoint/pred_tower0/map/while/box_nms/non_max_suppression/iou_threshold/_1)]]
```

**Comment by roborocklsm** [comment]
After struggling for 2 days, I found the solution:

Replace `step` function in  `model/homographies.py` by the following new funtion:
```
def step(i, probs, counts, images):

        with tf.device('/cpu:0'):
            # Sample image patch
            H = sample_homography(shape, **config['homographies'])
            H_inv = invert_homography(H)
            warped = H_transform(image, H, interpolation='BILINEAR')
            count = H_transform(tf.expand_dims(tf.ones(tf.shape(image)[:3]), -1),
                                H_inv, interpolation='NEAREST')[..., 0]

            # Predict detection probabilities
            warped_shape = tf.to_int32(
                    tf.to_float(shape)*config['homographies']['patch_ratio'])
            input_warped = tf.image.resize_images(warped, warped_shape)

        prob = net(input_warped)['prob']
        prob = tf.image.resize_images(tf.expand_dims(prob, axis=-1), shape)[..., 0]
        prob_proj = H_transform(tf.expand_dims(prob, -1), H_inv,
                                interpolation='BILINEAR')[..., 0]

        probs = tf.concat([probs, tf.expand_dims(prob_proj, -1)], axis=-1)
        counts = tf.concat([counts, tf.expand_dims(count, -1)], axis=-1)
        images = tf.concat([images, tf.expand_dims(warped, -1)], axis=-1)
        return i + 1, probs, counts, images
```
DON'T need to change any other code.

The error is simply due to program trying to do some ops on GPU but only supported by CPU. Hope this could help others met the same problem.

**Comment by siyuada** [comment]
@roborocklsm Really thanks for your share. 
I didn't figure out that for not familiar to tensorflow. So I just try to use python to sample H.
