### ISSUE TITLE
Visulize problem?

### ISSUE THREAD

**Issue by xlong0513** [rpautrat/SuperPoint#122]
Hi, I am in Step 2 now. can i see the detection results on synthetic shapes after step 1? It seems in [#15](https://github.com/rpautrat/SuperPoint/issues/15) the author got intermediate results. how can i get the same results?
PS: The files in `notebooks/` are from git, how can i get the same ones myself.

**Comment by rpautrat** [comment]
Hi, stop asking the same question in 3 different issues!
I just answered here: https://github.com/rpautrat/SuperPoint/issues/121#issuecomment-559091708

Furthermore, this question had already been addressed in previous issues (e.g. https://github.com/rpautrat/SuperPoint/issues/53).
