### ISSUE TITLE
Evaluating the repeatability on HPatches with MagicPoint

### ISSUE THREAD

**Issue by heiko134470** [rpautrat/SuperPoint#123]
Hi, I would like to thank you for your excellent work for Superpoint.

As you mentioned, in step 4 you evaluated repeatabilities on HPatches with magic-point which trained in step 3 several times.

Could you provide the results of repeatabilities on HPatches with magic point?

**Comment by rpautrat** [comment]
Hi,

You can find it in this notebook: https://github.com/rpautrat/SuperPoint/blob/master/notebooks/detector_repeatability_hpatches.ipynb

The names of the experiments mean the following:
- 'mp_synth-v11': MagicPoint trained on synthetic dataset
- 'mp_synth-v11_ha1': MagicPoint trained on synthetic dataset and evaluated with homographic adaptation
- 'mp_synth-v11_ha1_trained': MagicPoint retrained on Coco with the pseudo ground truth (evaluated without homographic adaptation)
