### ISSUE TITLE
Generate labels for coco 2014

### ISSUE THREAD

**Issue by heiko134470** [rpautrat/SuperPoint#128]
Hi rpautrat,

After performing the step 2): 
python export_detections.py configs/magic-point_coco_export.yaml magic-point_synth --pred_only --batch_size=5 --export_name=magic-point_coco-export1
I encountered a problem from COCO2014, invalid jpeg 

![image](https://user-images.githubusercontent.com/58684478/71251972-aaf06280-235e-11ea-8fe8-3a37f18c9b44.png)

Did you also encounter the problem?

**Comment by rpautrat** [comment]
Hi, no I never encountered this. Maybe one of the images in your COCO folder is corrupted? You should also check that the folder contains only images and nothing else.

**Comment by heiko134470** [comment]
Finally, I found a defect image in COCO folder. 
![image](https://user-images.githubusercontent.com/58684478/71337582-4106d180-2587-11ea-9e2f-a1df01153955.png)
