### ISSUE TITLE
about super point train

### ISSUE THREAD

**Issue by FangGet** [rpautrat/SuperPoint#13]
did you train descriptors? it seems hard to converge to a good descriptor feature map as in paper.

if you trained the whole pipeline successfully, can you tell what's the key to train descriptor well? I tried many times while get poor des performance

**Comment by rpautrat** [comment]
No, unfortunately I am also struggling to get a stable training with the descriptors. But I am working on it, and will update the ReadMe if I manage to get good descriptors.

**Comment by FangGet** [comment]
can you leave an email address? we can communicate about it, mine is fangasfrank at  gmail dot com

**Comment by rpautrat** [comment]
Sure.
