### ISSUE TITLE
Scale Invariancy

### ISSUE THREAD

**Issue by ufukefe** [rpautrat/SuperPoint#130]
Hello, thanks again for sharing your great work!

I am MSc student working on feature matching. I have done the demo using pretrained model and tried it on my dataset. For widebaseline cases it works pretty well, but for scale varying data it fails. I guess it is about homography adaptaion. 
In homographies.py, Ln 164
scales = tf.concat(
                [[1.], tf.truncated_normal([n_scales], 1, scaling_amplitude/2)], 0)

Parameters were defined as;
n_scales = 5 and scaling_amplitude=0.1 

Do you think if I change n_scales and scaling_amplitude with greater numbers makes it more scale invariant? Is there any other parameter should I arrange? Thanks :)

**Comment by rpautrat** [comment]
Hi,
You don't necessarily need to modify n_scales, but increasing scaling_amplitude would help indeed.
I would also recommend you to increase the 'scaling_amplitude' parameter in the config files that you use for training. This will allow more scale diversity in the training images set and thus the network will generalize better on different scales.

**Comment by ufukefe** [comment]
Thank you for fast response, I will try it. I could not understand for what 'scaling_amplitude' parameter in the config files used for exactly.  'scaling_amplitude' parameter in the config files were arranged to 0.2 while scaling_amplitude=0.1 in homographies.py. Should it be exactly twice? I guess it is not necessary.

**Comment by rpautrat** [comment]
The 'scaling_amplitude' of `homographies.py` is actually overwritten by the one in the config file. So you can just increase the 'scaling_amplitude' of the config file (e.g. to 0.4 or 0.5).

There is also a small nuance between the config files: 'scaling_amplitude' in `magic_point_shapes.yaml`, `magic_point_coco_train.yaml` and `super_point_coco.yaml` will change the scale factor of the images generated for training, while 'scaling_amplitude' in `magic_point_coco_export` will change the scale of the homographies used during homography adaptation. The best for you would be to increase both 'scaling_amplitude'.
