### ISSUE TITLE
Error in draw_points()

### ISSUE THREAD

**Issue by xlong0513** [rpautrat/SuperPoint#131]
Hi! I am in Step 4: Evaluating the repeatability on HPatches. And I want to compare MagicPoint with classical detector. First, I used the following command to get classical detectors repeatability.
`python export_detections_repeatability.py configs/classical-detectors_repeatability.yaml classical_detectors --export_name=harris_hpatches-repeatability`
It was ok. Then i use `detector_repeatability_coco.ipynb`  to see the evaluation, It gives me the following error
![2020-01-02 21-46-45](https://user-images.githubusercontent.com/35829321/71670377-9d999600-2daa-11ea-8639-2eb411719d17.png)

It seems the draw_keypoints() needs integer points.

**Comment by rpautrat** [comment]
Yes it seems so.

**Comment by rpautrat** [comment]
So why don't you convert the keypoints to integer?

**Comment by xlong0513** [comment]
Because `draw_keypoints()` has been called before for drawing `img1` keypoints. Should it be the same, if the points in img2 are float? And which code causes the difference of `integer` and `float`?
Thanks for reply.

**Comment by rpautrat** [comment]
But why did you change the notebook? There is no `get_true_keypoints` in the original notebook and this function apparently outputs floating points instead of integers. The notebook as it is currently online should have worked correctly.

 Also note that there is a notebook dedicated to repeatability for HPatches specifically: `notebooks/detector_repeatability_hpatches.ipynb` (I will update the ReadMe).

**Comment by xlong0513** [comment]
My fault. I have made a mistake when copying files. Actually i want to see the coco repeatability of MagicPoint, and i have modified the `magic-point_repeatability.yaml` as the following figure shows, 
![2020-01-06 23-03-10](https://user-images.githubusercontent.com/35829321/71826620-47459380-30d9-11ea-949b-6c2644bb0865.png)

but it gives me an error. Where am i wrong? Thanks a lot.
![2020-01-06 23-04-14](https://user-images.githubusercontent.com/35829321/71826628-4dd40b00-30d9-11ea-9a6c-4675d2b65379.png)

**Comment by rpautrat** [comment]
Step 5 is optional and is only useful if you want to evaluate repeatability on both HPatches and COCO (but evaluating on HPatches as in Step 4 could be enough). If you really want to evaluate repeatability on COCO as well, you need to generate COCO patches with `generate_coco_patches.py` and then use in the config file the following dataset:
```
name: 'patches_dataset'
    dataset: 'coco'
```
