### ISSUE TITLE
how to display .npz file?

### ISSUE THREAD

**Issue by liyandongpy** [rpautrat/SuperPoint#133]
after step2 and step4, i got two dirs 👍 

![image](https://user-images.githubusercontent.com/49861986/72703558-db5f3280-3b90-11ea-802d-680711950c00.png)

i got many npz files ,
![image](https://user-images.githubusercontent.com/49861986/72703614-0053a580-3b91-11ea-8cc8-a1ca6418e651.png)

i don't know how to display npz file. make image visable.

**Comment by rpautrat** [comment]
https://stackoverflow.com/questions/31368710/how-to-open-a-npz-file
