### ISSUE TITLE
Setting of lambda_d

### ISSUE THREAD

**Issue by ChunhuanLin** [rpautrat/SuperPoint#135]
Hi, as the positive and negative matches are imbalanced, lambda_d is set to make them balance. In the paper, lambda_d is set to 250, however, you set it to 0.05 in supoint_coco.yaml, which make them even more imbalanced.

**Comment by ChunhuanLin** [comment]
I have a related answer [here](https://github.com/rpautrat/SuperPoint/issues/100#issuecomment-567842417). But I still have some question about the details:
1. Is relu really necessary [here](https://github.com/rpautrat/SuperPoint/blob/95b5d161e89584087b20a2e7ee0a652109523998/superpoint/models/utils.py#L110)?
2. Does normalization of desc loss improve the performance of the results? And how much will it improve? I found the desc loss is hard to convergence using my own data.

**Comment by rpautrat** [comment]
Hi,

1. I applied the ReLU to obtain a similar effect as in the paper https://arxiv.org/pdf/1703.05593.pdf (see page 3, paragraph 'Matching layer'). But I think it would still work in a very similar way without the ReLU, I just didn't try without it.
2. I didn't observe a huge boost of performance with the normalization of desc loss in practice. If I remember correctly, it only gave a minor improvement and I don't remember how much.

Convergence of the desc loss has always been hard, whether there is a normalization or not. If you use your own data, you probably need to retune a bit the hyperparameters, like the lambda balancing the detector and desc losses or the lambda_d.

**Comment by ChunhuanLin** [comment]
Thanks a lot!
