### ISSUE TITLE
Size of synthetic images

### ISSUE THREAD

**Issue by paalpri** [rpautrat/SuperPoint#139]
Is there a reason why the synthetic images are resized to [120, 160]  ( as stated in the config file) 
When the coco images are scaled to [240, 320]. ( as in the default config in dataset file) 

And does it yield better results by using [240, 320] instead of the original coco size ? 

Thanks for any insight!

**Comment by rpautrat** [comment]
Hi,

If I remember correctly, the smaller size of the synthetic dataset was mainly there to reduce the memory space needed to store the dataset.
Regarding the size [240, 320] for COCO images, it allows both to have a fixed size for all images (and with dimensions divisible by 8) and to have a limited GPU memory consumption during training. But if memory is not a problem for you, you can certainly increase the size of the images during training.
