### ISSUE TITLE
Pretrained MagicPoint Model

### ISSUE THREAD

**Issue by NDer100KG** [rpautrat/SuperPoint#142]
Thanks for your implement of Superpoint !
Is it possible to release the trained magic point model?
Looking forward to it, thanks!

**Comment by rpautrat** [comment]
Is there are reason why you want MagicPoint specifically? Because if you only need the detector, you can still use the pretrained SuperPoint model and use only the detector part.

**Comment by NDer100KG** [comment]
Thanks for your reply.
Since MagicPoint is trained with vgg backbone for keypoints detection only, I think it may be somehow more accurate than SuperPoint?
Yet, just as your recommendation, it will be okay if using only the detector part of SuperPoint.
Thanks again~!

**Comment by rpautrat** [comment]
Well in practice, MagicPoint is not necessarily better than SuperPoint. Adding the descriptor head acts a bit as in multi task learning and actually helps the detector.

**Comment by jennyzhang2018** [comment]
Hi, I am trying to run your superpoint on openvino environment, but can't convert the sp_v6 with model optimizer to the IR format. Openvino support the translation for vgg_16 and vgg_19, maybe the MagicPoint model can do the translation. @rpautrat 
Thanks!

**Comment by rpautrat** [comment]
Hi, you can download the folder resulting from the training of MagicPoint [here](https://drive.google.com/file/d/1DhPNfT4_DbolRHb7yXnB7g4AeVvABt7G/view?usp=sharing). Not sure if that will solve your problem though...

**Comment by jennyzhang2018** [comment]
Thank you so much for your link, in fact I trained it too  with the same output you have, but seems I need that model.meta data, so I enabled the save meta data, didn't finish the training yet. Another question, if I need input_shape, it should be [N, H, W, C], N=1 or 2? C=3 or 1? @rpautrat  

Thanks!

**Comment by rpautrat** [comment]
N is the batch size: you can use whatever you want. I used N=32 for MagicPoint, and N=2 or 3 for SuperPoint, I couldn't fit more on my GPU.
C=1, the model is trained on grayscale images.

**Comment by jennyzhang2018** [comment]
Thank you very much for the reply! 
Got training result of both model.meta of magic-point_synth and superpoint_coco

after running python3 mo_tf.py --input_meta_graph sp_train_coco/model.ckpt-600000.meta --log_level DEBUG

Both got the similar error as:
........
[ WARNING ]  Configuration file for custom replacement with id 'ObjectDetectionAPIPSROIPoolingReplacement' doesn't exist
[ INFO ]  Failed to find custom replacement description with id 'ObjectDetectionAPIPSROIPoolingReplacement'
[ INFO ]  Skip replacer <class 'extensions.front.sub.Sub'> (graph_condition not satisfied)
[ 2020-09-02 10:39:26,438 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.split_normalizer.SqueezeAxis'>
[ 2020-09-02 10:39:27,456 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIMaskRCNNROIPoolingSecondReplacement'>
[ WARNING ]  Configuration file for custom replacement with id 'ObjectDetectionAPIMaskRCNNROIPoolingSecondReplacement' doesn't exist
[ INFO ]  Failed to find custom replacement description with id 'ObjectDetectionAPIMaskRCNNROIPoolingSecondReplacement'
[ 2020-09-02 10:39:27,501 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.tf.ObjectDetectionAPI.ObjectDetectionAPIMaskRCNNSigmoidReplacement'>
[ WARNING ]  Configuration file for custom replacement with id 'ObjectDetectionAPIMaskRCNNSigmoidReplacement' doesn't exist
[ INFO ]  Failed to find custom replacement description with id 'ObjectDetectionAPIMaskRCNNSigmoidReplacement'
[ 2020-09-02 10:39:27,547 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.tf.concat.Concat'>
[ 2020-09-02 10:39:27,721 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.ChangePlaceholderTypes.ChangePlaceholderTypes'>
[ 2020-09-02 10:39:27,770 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.ChangeCastOutputType.ChangeCastOutputType'>
[ WARNING ]  Change data type from <class 'numpy.float64'> to <class 'numpy.float32'> for node magicpoint/eval_tower0/truediv_1/Cast
[ WARNING ]  Change data type from <class 'numpy.float64'> to <class 'numpy.float32'> for node magicpoint/eval_tower0/truediv/Cast
[ WARNING ]  Change data type from <class 'numpy.float64'> to <class 'numpy.float32'> for node magicpoint/eval_tower0/truediv_1/Cast_1
[ WARNING ]  Change data type from <class 'numpy.float64'> to <class 'numpy.float32'> for node magicpoint/eval_tower0/truediv/Cast_1
[ 2020-09-02 10:39:27,945 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.tf.CTCGreedyDecoder.CTCGreedyDecoderReplacement'>
[ 2020-09-02 10:39:28,102 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.tf.bucketize.BucketizeFrontReplacer'>
[ 2020-09-02 10:39:28,154 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.tf.BlockLSTM.BlockLSTM'>
[ 2020-09-02 10:39:28,328 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.binary_quantize_normalization.BinaryFakeQuantizeNormalization'>
[ 2020-09-02 10:39:28,808 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.tf.BatchToSpaceNDToUpsample.BatchToSpaceToUpsample'>
[ 2020-09-02 10:39:28,982 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.tf.space_to_batch.BatchToSpaceNormalizer'>
[ 2020-09-02 10:39:29,034 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.rank_decomposer.RankDecomposer'>
[ 2020-09-02 10:39:29,208 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.split_normalizer.AttributedVariadicSplitToVariadicSplit'>
[ 2020-09-02 10:39:29,256 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.split_normalizer.AttributedSplitToSplit'>
[ 2020-09-02 10:39:29,900 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.tf.basic_lstm_cell.BasicLSTMCell'>
[ 2020-09-02 10:39:30,395 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.AttributedPadToPad.AttributedPadToPad'>
[ 2020-09-02 10:39:30,443 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.AttributedGatherNormalizer.AttributedGatherNormalizer'>
[ 2020-09-02 10:39:30,616 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.AttributedClampNormalizer.AttributedClampNormalizer'>
[ 2020-09-02 10:39:30,665 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.ATenToEmbeddingBag.AtenToEmbeddingBag'>
[ 2020-09-02 10:39:30,713 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.tf.assign_elimination.AssignSubElimination'>
[ 2020-09-02 10:39:30,843 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/detector/conv2/bn/AssignMovingAvg_1
[ 2020-09-02 10:39:30,843 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv4_1/bn/AssignMovingAvg
[ 2020-09-02 10:39:30,843 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv2_1/bn/AssignMovingAvg_1
[ 2020-09-02 10:39:30,843 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/detector/conv2/bn/AssignMovingAvg
[ 2020-09-02 10:39:30,843 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv4_2/bn/AssignMovingAvg_1
[ 2020-09-02 10:39:30,843 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv4_1/bn/AssignMovingAvg_1
[ 2020-09-02 10:39:30,844 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv3_1/bn/AssignMovingAvg
[ 2020-09-02 10:39:30,844 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv1_1/bn/AssignMovingAvg
[ 2020-09-02 10:39:30,844 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/detector/conv1/bn/AssignMovingAvg
[ 2020-09-02 10:39:30,844 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv4_2/bn/AssignMovingAvg
[ 2020-09-02 10:39:30,844 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv3_1/bn/AssignMovingAvg_1
[ 2020-09-02 10:39:30,844 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv1_1/bn/AssignMovingAvg_1
[ 2020-09-02 10:39:30,844 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv2_1/bn/AssignMovingAvg
[ 2020-09-02 10:39:30,844 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv1_2/bn/AssignMovingAvg_1
[ 2020-09-02 10:39:30,844 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv3_2/bn/AssignMovingAvg_1
[ 2020-09-02 10:39:30,845 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv2_2/bn/AssignMovingAvg_1
[ 2020-09-02 10:39:30,845 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv2_2/bn/AssignMovingAvg
[ 2020-09-02 10:39:30,845 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv1_2/bn/AssignMovingAvg
[ 2020-09-02 10:39:30,845 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/vgg/conv3_2/bn/AssignMovingAvg
[ 2020-09-02 10:39:30,845 ] [ DEBUG ] [ assign_elimination:51 ]  AssignSub op was removed magicpoint/train_tower0/detector/conv1/bn/AssignMovingAvg_1
[ 2020-09-02 10:39:30,890 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.tf.assign_elimination.AssignElimination'>
[ 2020-09-02 10:39:31,018 ] [ DEBUG ] [ assign_elimination:36 ]  Assign op was removed magicpoint/Adam/Assign_1
[ 2020-09-02 10:39:31,019 ] [ DEBUG ] [ assign_elimination:36 ]  Assign op was removed magicpoint/Adam/Assign
[ 2020-09-02 10:39:31,063 ] [ DEBUG ] [ class_registration:282 ]  Run replacer <class 'extensions.front.tf.assign_elimination.AssignAddElimination'>
[ ANALYSIS INFO ]  It looks like there is IteratorGetNext as input
**Run the Model Optimizer with:
                --input "magicpoint/IteratorGetNext:0[-1 -1 -1 1],magicpoint/IteratorGetNext:1[-1 -1 -1],magicpoint/IteratorGetNext:2[-1 -1 2],magicpoint/IteratorGetNext:3[-1 -1 -1]"**
And replace all negative values with positive values
[ ERROR ]  Exception occurred during running replacer "None" (<class 'extensions.front.tf.assign_elimination.AssignAddElimination'>): Data flow edge coming out of AssignAdd node magicpoint/Adam
[ 2020-09-02 10:39:31,193 ] [ DEBUG ] [ main:322 ]  Traceback (most recent call last):
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 288, in apply_transform
    for_graph_and_each_sub_graph_recursively(graph, replacer.find_and_replace_pattern)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/middle/pattern_match.py", line 58, in for_graph_and_each_sub_graph_recursively
    func(graph)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/front/common/replacement.py", line 148, in find_and_replace_pattern
    apply_pattern(graph, action=self.replace_sub_graph, **self.pattern())
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/middle/pattern_match.py", line 95, in apply_pattern
    action(graph, match)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/extensions/front/tf/assign_elimination.py", line 68, in replace_sub_graph
    raise Error('Data flow edge coming out of AssignAdd node {}'.format(node.id))
mo.utils.error.Error: Data flow edge coming out of AssignAdd node magicpoint/Adam

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/main.py", line 309, in main
    ret_code = driver(argv)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/main.py", line 270, in driver
    ret_res = emit_ir(prepare_ir(argv), argv)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/main.py", line 235, in prepare_ir
    graph = unified_pipeline(argv)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/pipeline/unified.py", line 29, in unified_pipeline
    class_registration.ClassType.BACK_REPLACER
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 334, in apply_replacements
    apply_replacements_list(graph, replacers_order)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 324, in apply_replacements_list
    num_transforms=len(replacers_order))
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/utils/logger.py", line 124, in wrapper
    function(*args, **kwargs)
  File "/opt/intel/openvino_2020.4.287/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 304, in apply_transform
    )) from err
mo.utils.error.Error: Exception occurred during running replacer "None" (<class 'extensions.front.tf.assign_elimination.AssignAddElimination'>): Data flow edge coming out of AssignAdd node magicpoint/Adam

Thanks!

**Comment by rpautrat** [comment]
Hi, I have no experience with Openvino, so I cannot help you on this...

**Comment by jennyzhang2018** [comment]
@rpautrat sure, thanks!
