### ISSUE TITLE
hfnet feature matching VS colmap sift feature matching 

### ISSUE THREAD

**Issue by yuancaimaiyi** [rpautrat/SuperPoint#143]
@rpautrat 
sorry to bother you !
![siftAndSuperpoint](https://user-images.githubusercontent.com/28293910/75137512-bf682700-5722-11ea-91c4-a1291b5910aa.png)
as you sea ,In the picture ,the up is the result of " colmap sift feature matching ",the bottom is the result of "hfnet feature matching ". There are a lot of mismatches about hfnet  feature matching .
A lot of papers show that superpoint is better than sift, so I'm confused . Am I wrong?

**Comment by rpautrat** [comment]
Hi,

1+1=2 doesn't mean that the result of all additions is 2. So yes, that's one example where SIFT seems to be better, but that doesn't mean anything.

SuperPoint is better than SIFT in some cases, but SIFT is still better in other metrics/datasets, that's all.
