### ISSUE TITLE
About the network

### ISSUE THREAD

**Issue by zhanggaojian** [rpautrat/SuperPoint#146]
Hi,Thank you for your great work! I am confused about the training network，about the step（1），is the network of superpoint used to train magicpoint？I am looking forward to your reply.Thanks!

**Comment by rpautrat** [comment]
Hi,

The network used during training is specified in the config file, in the field model->name. In the case of step (1), the config file specifies model->name->'magic_point', so it is the network of MagicPoint only which is used.

**Comment by zhanggaojian** [comment]
Thank's for your reply, I am very looking forward to your pytorch version.Thanks very much!

**Comment by rpautrat** [comment]
As said here: https://github.com/rpautrat/SuperPoint/issues/127#issuecomment-596502660, there is already a Pytorch version of SuperPoint, based on this repo. So I don't think that there is a need to release it in the end.
