### ISSUE TITLE
Summarize the output in a d-dimensional vector

### ISSUE THREAD

**Issue by marijnl** [rpautrat/SuperPoint#147]
have you tried to summarize the output of the net into one d-dimensional feature vector?
Looking up n descriptors per image query is computationally too expensive for my use-case.

To speed up retrieval i'm thinking of training an FC layer that summarizes the output of the net.
Any experience doing this?

**Comment by rpautrat** [comment]
Hi, so you want an image descriptor, not a feature descriptor, right? This is a different problem than the one solved by SuperPoint. But you can still leverage the SuperPoint local descriptor by adding for example a [NetVLAD layer](https://www.di.ens.fr/willow/research/netvlad/) after the descriptor prediction to get a global descriptor.

**Comment by marijnl** [comment]
Thanks for the pointer. The suggested is exactly what i was looking for!
