### ISSUE TITLE
Trying to obtain more feature points

### ISSUE THREAD

**Issue by jiyun-xiao** [rpautrat/SuperPoint#150]
Hi,

Thank you for your very well-written repo! I am trying to have around 1000 features when I do inference with the superpoint model.   But I always get exactly 600 features when I do inference with the superpoint model I trained. 

Here are the efforts I made to try to obtain more feature points:

I set the top_k = 2000 in config/superpoint_coco.yaml, but the super-point model that I exported still give exactly 600 points for any image that I input into it. (The detection threshold is the default value 0.001)

I thought that I was not getting enough features from magicpoint model, so I double checked that top_k was commented out in config/magic-point_coco_train.yaml and config/magic-poing_coco_export.yaml, but the magic-point model that I exported give exactly 1000 points for any image that I input into it. 

I thus looked into the code for anywhere that might have caused the number of features to be exactly 1000 or exactly 600, but I haven’t found it.

I’m wondering if you could shine some light on what the problem might be? Thank you very much for your help!

**Comment by rpautrat** [comment]
Hi,

What code are you using to get the keypoints? After inference with the model, are you directly using the 'pred' entry in the output? Or are you using the 'prob' (or 'prob_nms' if you want to apply NMS first) and then filtering it to keep the top_k points?

The 'pred' entry should indeed depend on the `top_k` and `detection_threshold` of the config file, but if the threshold is too high, you won't get enough keypoint (especially if the image sizes are small). I suggest doing the second option instead: use the 'prob_nms' entry and use a `np.where(output['prob_nms'] > 0)` to keep all the positive locations, and finally keep only the top_k best scores in it.

**Comment by jiyun-xiao** [comment]
Hi,

Thank you so much for your suggestion! I was indeed using prob_nms as the output, and I wasn't doing any filtering. But here is a demonstration of the effect that I was talking about. The code is the newly-pulled SuperPoint with no revision, other than print("kp1 length: " + str(len(kp1)))
and print("kp2 length: " + str(len(kp2))) that I added in match_features_demo.py. The data is COCO_train2014. The model is trained with a top_k: 2000 in config/superpoint_coco.yaml. The command is: python3 match_features_demo.py sp_0520 /home/jiyunxiao/SuperPoint_dataset/COCO_coco_subset/train2014/COCO_train2014_000000000404.jpg /home/jiyunxiao/SuperPoint_dataset/COCO_coco_subset/train2014/COCO_train2014_000000000404.jpg

![Screenshot from 2020-05-26 23-08-02](https://user-images.githubusercontent.com/61214399/82983948-fb22bf00-9fa5-11ea-9c58-29952968295b.png)
![Screenshot from 2020-05-26 23-07-22](https://user-images.githubusercontent.com/61214399/82983965-ffe77300-9fa5-11ea-89cf-ca989f36e22a.png)
![Screenshot from 2020-05-26 23-06-37](https://user-images.githubusercontent.com/61214399/82983975-04ac2700-9fa6-11ea-9a9a-538e4c1b3afb.png)
![Screenshot from 2020-05-26 23-05-50](https://user-images.githubusercontent.com/61214399/82983982-08d84480-9fa6-11ea-88bb-12a29fe6fa68.png)
![Screenshot from 2020-05-26 23-04-39](https://user-images.githubusercontent.com/61214399/82983992-0bd33500-9fa6-11ea-9ca2-4676a637a264.png)
![Screenshot from 2020-05-26 23-03-11](https://user-images.githubusercontent.com/61214399/82984003-11c91600-9fa6-11ea-8913-77e51292eb9e.png)


In each of these screenshots, the upper left window is the superpoint result visualization done by match_features_demo.py, the upper right window is the terminal output that is currently running match_feature_demo.py, the lower left window is the original picture, the lower right window is the code of match_features_demo.py. It shows the location where I added print("kp1 length: " + str(len(kp1))) and print("kp2 length: " + str(len(kp2))).

As you can see in the upper right window of all of 6 these screenshots, kp1 length: 600, kp2 length: 600 in all 6 screenshots. I think from looking at the picture, many of these might have more than 600 keypoints. And also, even if they indeed have only around 600 keypoints, it is a bit hard to believe that it is just coincidence that all 6 pictures have exactly 600 points. Thank you very much!

**Comment by rpautrat** [comment]
Hi, sorry for the late reply.

I indeed get the same result as you on my machine. The problem is that the model that I exported had the parameter top_k set to 600, so you could only have at most 600 keypoints when using this model. Sorry for that.

I now re-exported a new model, this time with no specified top_k. You should now be able to use as many keypoints as you want by pulling the latest changes.

**Comment by jiyun-xiao** [comment]
Hi rpautrat,

Thank you so much for the effort you put into this! But after running the new model using match_features_demo.py and COCO pictures, I still get exactly 600 keypoints on each of those pictures...

**Comment by rpautrat** [comment]
Hi,

Are you sure you pulled the last changes of the master branch? On my machine I now get 1000 keypoints per image (default parameters). Whereas I was also having 600 keypoints like you before pushing the last change.

**Comment by rpautrat** [comment]
Hi, yes of course if you use the saved_model.pb of the old checkpoint you will still have the 600 keypoints.

The error you had with the new version is probably a Tensorflow compatibility issue. Which version of Tensorflow are you using? I exported and tested the new checkpoint with TF 1.14.

**Comment by jiyun-xiao** [comment]
Yes that seems to be the cause of the bug, my version of Tensorflow is TF 1.6, and it seems that TF1.6 can only work with NonMaxSuppressionV2. Thank you so much for your help!

**Comment by haithink** [comment]
Is keep_k_best  equal to 600 in match_features_demo.py?

**Comment by rpautrat** [comment]
It is 1000 by default: https://github.com/rpautrat/SuperPoint/blob/aee614f49c173704295421b9c0030cec89bf05a7/superpoint/match_features_demo.py#L96

**Comment by haithink** [comment]
> It is 1000 by default:
> 
> https://github.com/rpautrat/SuperPoint/blob/aee614f49c173704295421b9c0030cec89bf05a7/superpoint/match_features_demo.py#L96
Yes, I am asking jiyun-xiao if the keep_k_best in his match_features_demo.py has been set to 600。
