### ISSUE TITLE
about NN mAP&M.Score

### ISSUE THREAD

**Issue by coper16** [rpautrat/SuperPoint#153]
Hello,thank you for your great work!!
I want to get NN mAP score and M.Score about SuperPoint(training by myself) descriptor.
Is there output program of this?

**Comment by rpautrat** [comment]
Hi, no these two metrics have not been implemented in this repo. We only relied on the homography estimation to evaluate the descriptors.

**Comment by coper16** [comment]
Thanks for reply.
I see.
In your paper, you may use these evaluation method(in Table 4.).
so, if it is possible, can I get that code?

**Comment by rpautrat** [comment]
Hi, this is not my paper, this repo is a reimplementation of the original SuperPoint developped by MagicLeap in Tensorflow. The original authors are Daniel DeTone, Tomasz Malisiewicz and Andrew Rabinovich.
So if you want these metrics I am afraid that you need to implement them by yourself...

**Comment by coper16** [comment]
Oh.I'm sorry,i have misunderstood!
I'll try it!
Thanks :)
