### ISSUE TITLE
Does dataset need to shuffle?

### ISSUE THREAD

**Issue by scarftdd** [rpautrat/SuperPoint#154]
Hi,
I want to know if the coco dataset need to shuffle at the training process. And I add the following code in coco.py
`files_len = len(files['image_paths'])
data = data.shuffle(files_len)`

Is the code correct?

Thank you.

**Comment by rpautrat** [comment]
Hi,
Indeed if I remember correctly, there is currently no shuffling of the COCO images. The code you added should work, yes.

**Comment by scarftdd** [comment]
Thank you for reply.
