### ISSUE TITLE
Actual Working TF Version is 1.12

### ISSUE THREAD

**Issue by jamesguoxin** [rpautrat/SuperPoint#155]
In the document, the authors indicated that we need to install TF 1.6, this version is not working with match_features_demo.py, after spending some time on debugging, I found the working version for TF is 1.12.

In case anyone encounters similar problem, I left the note here

**Comment by rpautrat** [comment]
Thank you for the useful remark! The demo was indeed added later and is now using a later version of Tensorflow. I will update the Readme.

**Comment by zhgx-ch** [comment]
Actually,my code can be processd on tf 1.13.0
