### ISSUE TITLE
Running speed problem

### ISSUE THREAD

**Issue by GuoFeng-X** [rpautrat/SuperPoint#160]
Compared with the original pre-trained model (superpoint_v1.pth), does it run slower?

**Comment by rpautrat** [comment]
Hi, yes I think the current version is slower than the pretrained model, but I don't have a proper comparison between the two to be honest.

**Comment by kevinlisun** [comment]
Yes. The TensorFlow implementation is approximately 4 times slower than pre-trained model (superpoint_v1.pth). I dont think the two toolboxes have that big difference. Any ideas about it?

**Comment by rpautrat** [comment]
Hi,
You can have a look at [this issue](https://github.com/rpautrat/SuperPoint/issues/109) to get some directions to improve the runtime efficiency.
