### ISSUE TITLE
descriptor problem

### ISSUE THREAD

**Issue by Yvaine** [rpautrat/SuperPoint#163]
Thank you for your project very much, but I have some problems confused me very much. 
1.Why the cell_distances threshold is 8? when coord_cells represent the center of 8x8, then its range is [-4,4] if it is in center.
such as two coord_cells is [4,12], if a wraped point is 10, |4-10| < 8, |12-10| < 8, so the wraped point belongs to the two cells, that is werid, should one point match one point, not one point match two points?
2. Why use all cell descriptor to calculate loss? when the cell has no keypoint, it has no meanless, if it is plain texture, or all noise, it is no things to learn.
Wish for your answer to my confused problem

**Comment by rpautrat** [comment]
Hi,
1. Your reasoning is correct, but it actually doesn't really matter if a warped point is at a distance less than 8 of two different cells. As long as the warped point is close enough to a cell, it should be considered as a positive match. There is anyway no one-to-one mapping among warped points and cells, as several warped points can fall in the same cell after the effect of warping.
2. I agree that using all cells - including the uninformative ones - is a weakness of SuperPoint, and that it would benefit from ignoring those cells during training. The question is how to detect those textureless cells. One could indeed rely on the detection score, threshold it and mask the cells with low probability. Or use a reliability head as in [R2D2](https://arxiv.org/abs/1906.06195). In any case, this was not in the original SuperPoint paper.

**Comment by Yvaine** [comment]
Thank you for reply,
  If sum of s less than WcxHc? My test is 2400 when Wc=30 and Hc  = 40, that's correct?

**Comment by rpautrat** [comment]
The sum of s will depend on the homography, but it should on average be around 2 x Wc x Hc (factor 2 because each pair of (cell, warped cell) is present twice). For the identity function, the sum of s should be exactly 2 x Hc x Wc for example, so that seems correct in your case.

**Comment by Yvaine** [comment]
Understand, thank you. I have last one question.
When calculate the descriptor loss, I have two methods
1. Only use the descriptor sample from label as the positive match regardless the keypoint is detected or not.
2. Use descriptor sample from keypoint detected score high and wraped descriptor from that keypoint wraped as positive match.
Which methods will better?

**Comment by rpautrat** [comment]
In the original implementation, option 1 was used. But I think it would make sense and probably yield better results with option 2. So I would recommend trying the second one.

**Comment by Yvaine** [comment]
Thank you, I will try second method.
