### ISSUE TITLE
About detector evaluation.

### ISSUE THREAD

**Issue by xlong0513** [rpautrat/SuperPoint#166]
Hi, sorry to disturb. I want to run `detector_evaluation_magic_point.ipynb`, and I got 2 questions.
1.  Does the parameter `data/add_augmentation_to_test_set` needs to change in training? Or it is only change in test.
2. Why the parameter `data/suffix` is different for magicpoint and classical detectors. In `magic-point_shapes.yaml`, it is `v6`, and in `classical-detectors_shapes.yaml`, it is `v5`. I think they should be same because magicpoint and classical detectors should use the same data to compare?

**Comment by xlong0513** [comment]
I see. Thanks for the answer.

**Comment by xlong0513** [comment]
Hi, @rpautrat, I want to ask another question in training magicpoint and superpoint.  
1. If  in the Step 3 and Step 6, we use the same detections from Step 2, then they are actually same step. Right?
2. Suppose 1 is right, if I want to train magicpoint and superpoint respectively, I should export detections on MS-COCO with the `Homographic Adaptation` diable for magicpoint, and enable for superpoint. Am i right?

**Comment by rpautrat** [comment]
Hi,

1. If you use several rounds of step 2+3, then after a second round the export will be different. I suggest doing 2 rounds, so export (step 2), train MagicPoint (step 3), export (step 2 again), then train SuperPoint (step 6). In general, step 3 and 6 are different as the networks trained in both are different (with or without descriptors).

2. Homographic adaptation should always be used when exporting the detections, whether it is for MagicPoint or SuperPoint. It can only improve the quality of your pseudo label.

**Comment by xlong0513** [comment]
Hi, I got it.  You mean the difference is with or without descriptors. But why the `Homographic adaptation ` should be used for MagicPoint, cause in the original paper, it is for SuperPoint. 
2. And I have another question by the way. In `deector_repeatability_coco.ipynb`, I found the number of keypoints of MagicPoint is less than 300. And the numbers of the original image and the patch are not equal. As follows,
![2020-08-30 13-41](https://user-images.githubusercontent.com/35829321/91652177-1cc0a480-eac7-11ea-9cf7-eb1aea73a80b.png)


How can I get a stable detection result as the classical methods.

**Comment by rpautrat** [comment]
Hi,

1. MagicPoint is the detector trained on synthetic data only (so without homography adaptation). Then we use homography adaptation to create the pseudo ground truth on COCO and train the detector+descriptor on it to get SuperPoint. The transition between the two (detector only trained on COCO images with homography adaptation) is also still called SuperPoint in the original paper I think.

2. The number of points detected by MagicPoint depends on the detection threshold that is used. If it is too high, less than 300 points will be detected. To ensure always using 300 points, you can lower the threshold to 0:
`confidence_thresholds = [0, 0]`

**Comment by xlong0513** [comment]
Thanks for the reply. I got it. Please open this issue for now, and I will test it.

**Comment by xlong0513** [comment]
Hi, it works by lowering the threshold to 0. However, the repeatability result is weird, as follows,
![图片](https://user-images.githubusercontent.com/35829321/91954913-07e94880-ed35-11ea-955f-85b266bc7590.png)
The repeatability of MagicPoint is very high, while the classical methods are too low. I have checked the `plot_imgs` results, and they are very similar. My code is here:
![图片](https://user-images.githubusercontent.com/35829321/91955774-3e739300-ed36-11ea-9761-483c1b80df1c.png)


The difference should not be so huge. Did you ever have this problem? Thanks.

**Comment by rpautrat** [comment]
Instead of using a threshold of 0, you can maybe use a very small one. Because there could be situations with low texture images where it doesn't make sense to extract 300 points, and in that case using a threshold of 0 will still keep very bad keypoints.
But even with that, I am surprised that you get such a huge difference...

**Comment by xlong0513** [comment]
Yeah, I have tried a few values. However,the results never change, always the four values in the picture. Something is wrong maybe.

**Comment by rpautrat** [comment]
Can you show the images with keypoint detections of the classical methods that you get?

**Comment by xlong0513** [comment]
Sure. From top to bottom, FAST, Harris, Shi-Tomas, magicpoint.

![harris-1](https://user-images.githubusercontent.com/35829321/91976656-e055a880-ed53-11ea-9b93-939a6f79e691.png)
![shi-1](https://user-images.githubusercontent.com/35829321/91976697-f499a580-ed53-11ea-9991-d23c94dcc7df.png)
![mp1](https://user-images.githubusercontent.com/35829321/91976734-03805800-ed54-11ea-81eb-b9712b12ec59.png)

**Comment by rpautrat** [comment]
Thanks. The detections look fine for all of them, so I have no clue why you would suddenly have such low scores for the classical methods...
And so when you keep the original detection thresholds, the repeatability is much better? If that's the case, I would just keep the 0 threshold for MagicPoint and the original thresholds for the others, as these thresholds were providing 300 points most of the time anyway.

**Comment by xlong0513** [comment]
Thanks for the advice. I think the more important question thats why modifying the thresholds has no influence on repeatability results. I mean, no matter how I change the threshlods, the repeatability values remain the same. Did the computation use all the detection results?
Besides,  I found the number of coco repeatability result of MagicPoint is 900, while the number of classical methods is 600. Is this normal?

**Comment by rpautrat** [comment]
I think that if you really use a high threshold, you will see different repeatability values, due to the fact that you will evaluate with less than 300 points. But otherwise the repeatability values shouldn't change.

There is basically a double filtering: first all the keypoints with a score lower than the threshold are removed, then with keep the 300 best remaining keypoints. So it makes sense that you get the same numbers when varying the threshold at low thresholds, because you will still keep more than 300 points after the first filtering and the top 300 points will remain the same.

If by number of repeatability results you mean number of images on which it is evaluated, no it is not normal. You should use the same number for all experiments. This number is specified in the config file of your repeatability experiments ('eval_iter' parameter). That might explain the difference of performance you observed: the last 300 images might be much harder than the 600 first ones...

**Comment by xlong0513** [comment]
ooh... Maybe I have done something wrong. I will try again. Great thanks.

**Comment by rpautrat** [comment]
I am closing this now, feel free to reopen it if you still have questions.
