### ISSUE TITLE
Fine-tuning with the pre-trained model on my own model

### ISSUE THREAD

**Issue by JiahaoXia** [rpautrat/SuperPoint#167]
I want to use SuperPoint to find corresponding points on my own dataset.
How can I do fine-tuning with the pre-trained model on my dataset? 
Or I need to training from the MagicPoint?

**Comment by rpautrat** [comment]
Hi,
Sorry for the late answer. Fine-tuning is not possible with the current framework, but can be easily added to the current code. Adding a line `net.load(output_dir)` on line 22 of `experiment.py` would probably work for example, if you want to resume the training from the output_dir.
But this won't be possible from the exported model provided in this repo. You would need to use the original training files, which I can provide if you want. Do you want to retrain MagicPoint only (keypoints only) or also the descriptors with SuperPoint?

**Comment by JiahaoXia** [comment]
Thank you for your kind reply!
I think I also need the descriptors with SuperPoint.
Could you please send it to my email (jiahaoxia1993@gmail.com)?

**Comment by rpautrat** [comment]
Sure, I'll send them to you!

**Comment by SungbinSon** [comment]
Hi,
i want to detect keypoint on Semiconductor images, so i want to retrain this model using my own dataset,
Could you provide the training Code and descriptors superpoint? 
my email is sbson0621@gmail.com

**Comment by ham-work** [comment]
Hi,
I think I would need the keypoints and descriptors also, to do some training testing on my own dataset.

Would it be possible to provide the keypoints and descriptors for both Magicpoint and Superpoint, please?

my email is akinnunenuva@gmail.com

Thank you!

**Comment by lililiiiiiiiiii** [comment]
> Thank you for your kind reply!
> I think I also need the descriptors with SuperPoint.
> Could you please send it to my email ([jiahaoxia1993@gmail.com](mailto:jiahaoxia1993@gmail.com))?

can you send the files to me? thanks! leeyang@mail.ustc.edu.cn

**Comment by lililiiiiiiiiii** [comment]
can you send the files to me? thanks! leeyang@mail.ustc.edu.cn

**Comment by noahzn** [comment]
> Hi, Sorry for the late answer. Fine-tuning is not possible with the current framework, but can be easily added to the current code. Adding a line `net.load(output_dir)` on line 22 of `experiment.py` would probably work for example, if you want to resume the training from the output_dir. But this won't be possible from the exported model provided in this repo. You would need to use the original training files, which I can provide if you want. Do you want to retrain MagicPoint only (keypoints only) or also the descriptors with SuperPoint?

Hi @rpautrat Could you also send the coco-pretrained checkpoints of superpoint to me? I need it to fine-tune on my own data. Thanks in advance.

n.zhang@utwente.nl

**Comment by rpautrat** [comment]
Hi, the links to the pre-trained models is in the ReadMe: https://github.com/rpautrat/SuperPoint?tab=readme-ov-file#fine-tuning-a-pretrained-model

**Comment by noahzn** [comment]
> Hi, the links to the pre-trained models is in the ReadMe: https://github.com/rpautrat/SuperPoint?tab=readme-ov-file#fine-tuning-a-pretrained-model

oh, I just found that the two sp_v6 are different. The one in the pretrained_models is the exported one. Thank you!
