### ISSUE TITLE
PATH problem

### ISSUE THREAD

**Issue by zt-Github-1** [rpautrat/SuperPoint#171]
Hi,I'm sorry to disturb.
I have a problem about PATH,  When I run your code, I saw Almost every.py file of you has the import of Settings in Superpoint, I want to know what content is stored in this Settings file. my personal understanding it is to store the location path of the output file, so I specified the path of EXPER_PATH and DATA_PATH, but the program reported an error, I don't know why.  so I'm looking forward to your help to answer it. Thanks.

**Comment by rpautrat** [comment]
Hi,

EXPER_PATH should be the path to your base folder where the experiments will be stored. For example if  `EXPER_PATH=~/Documents/experiments`, then the output of an experiment named <exp_name> will be stored in `~/Documents/experiments/<exp_name>`.

Similarly for DATA_PATH, it should be the root path to the folder containing the train and test datasets. For example you can have `DATA_PATH=~/Documents/datasets`, and store the COCO dataset in `~/Documents/datasets/COCO`.

I hope this makes sense to you, let me know if not.

**Comment by zt-Github-1** [comment]
Actually, I think so too, but when I run the experiment.py file with python experiment.py trian configs/ magic-point_shapes.yaml magic-point_synth, the following error appears. I am not sure if it is caused by the path change.

![image](https://user-images.githubusercontent.com/64679738/95806208-ba9bc600-0d39-11eb-9021-da0e34b6791d.png)

**Comment by rpautrat** [comment]
Can you put the full error message? I can't see the actual error...

**Comment by zt-Github-1** [comment]
Sorry to reply you so late, the previous problem has been resolved. 
In fact, I have encountered a problem that bothers me more. I have inquired many methods and have not solved it, but the same error is reported, so I want to ask you
![Uploading Screenshot from 2020-10-18 20-30-36.png…]()
This is the result after I execute ‘ python experiment.py train configs/magic-point_shapes.yaml magic-point_synth ’. The final ‘ KeyError:'CUDA_VISIBLE_DEVICES ' is the problem that bothers me. If you have a solution, please help me.Thanks.

**Comment by rpautrat** [comment]
Hi, do you have a GPU, with proper Nvidia drivers and the right version of CuDnn and Cuda to be compatible with your version of tensorflow?

**Comment by zt-Github-1** [comment]
Yes, my graphics model is Nvidia Geforce960M; And  I used the environment TensorFlow1.12, Cuda9.1, CudNN7.6 for Windows； TensorFlow1.12, Cuda9.0, CudNN7.6 for Linux; both environments have reported the same error.
Oh! I found a mistake in my question, KeyError:'CUDA_VISIBLE_DEVICES ' was generated when I was executing 'python export_DETECtions.py CONFIGs/magic-point_COCO_export. Yaml Magic-point_Synth --pred_only --batch_size=5 --export_name= magic-point_cox-Export1'.

**Comment by rpautrat** [comment]
I see. This error has already happened to some people and could be sometimes solved by changing the line 59 in `experiment.py` from `return len(os.environ['CUDA_VISIBLE_DEVICES'].split(','))` to `return 1`.
For some Cuda installations it seems that the environment variable CUDA_VISIBLE_DEVICES is not set, so this command bypass it and automatically assumes that there is one GPU available. Let me know if that helps.

**Comment by zt-Github-1** [comment]
Thank you very much, this has been very useful to me, the program is no longer reporting this error.

**Comment by rpautrat** [comment]
Great, I'm glad you solve your issue!
