### ISSUE TITLE
Descriptor Matching with knn

### ISSUE THREAD

**Issue by fatihmd** [rpautrat/SuperPoint#176]
Hello,

In my scenario, I resize the input image by half of its w and h, than extract superpoint features. Based on their descriptors, I have  used the opencv knn matcher to match those descriptors as shared below. But for this method, I couldn't found the optimal ratio threshold. Moreover, features are not on the same plane therefore I couldn't use the homography to get inliers. Could you help me for better superpoint descriptor matching method that give higher correct match rate, thanks in advance.

```
matcher = cv2.DescriptorMatcher_create(cv2.DescriptorMatcher_FLANNBASED)
knn_matches = matcher.knnMatch(descriptors1, descriptors1, 2)

ratio_thresh = 0.7
good_matches = []
for m,n in knn_matches:
	if m.distance < ratio_thresh * n.distance:
		good_matches.append(m)

ids0 = np.array([m.trainIdx for m in good_matches])
ids1 = np.array([m.queryIdx for m in good_matches])
```

**Comment by rpautrat** [comment]
Hi,
You don't necessarily need to use the ratio test on SuperPoint matches, usually using the mutual nearest neighbor approach (the two points should be symmetrically matched) gives already good results.
But if you want to use the ratio test, according to [Image Matching Across Wide Baselines: From Paper to Practice](https://arxiv.org/pdf/2003.01587.pdf) (Fig 11), a good ratio for SuperPoint is around 0.9 or 0.95.

**Comment by fatihmd** [comment]
Thanks for the answer, I have tried the ratio test around 0.9-0.95 but there are many mismatches that makes the PnP calculation fails even with RANSAC. I am going to try mutual NN as you adviced. If you have any further advices I will be appreciated if you share them. Thanks again.

**Comment by rpautrat** [comment]
Mutual NN has always worked very well for me, so I hope it should work for you.

Depending on your application, if you don't care about runtime, you can also run the homography adaptation at test time with a small number of homographies (10-30 homographies). This will produce very clean and repeatable keypoints at least.

**Comment by fatih4d** [comment]
Is it possible to share with me an example of homographic adaptation at test time? In my test scenario, I have two different superpoint sets, lets call the m set A and B. I applied knn repeatedly to get the matches between those sets A and B. Even I have apply the knn with same parameters, the returned matched features output are not coming same. What I understood is that homographic adaptation will help me in getting it stable and repeatable. Thanks in advance.

**Comment by fatihmd** [comment]
Is it possible to share with me an example of homographic adaptation at test time? In my test scenario, I have two different superpoint sets, lets call the m set A and B. I applied knn repeatedly to get the matches between those sets A and B. Even I have apply the knn with same parameters, the returned matched features output are not coming same. What I understood is that homographic adaptation will help me in getting it stable and repeatable. Thanks in advance.

**Comment by rpautrat** [comment]
Hum, the matched features should always be the same normally, there is nothing stochastic in the current pipeline. So you should double-check why you get different results each time.

Otherwise, to use homographic adaptation at test time, you would need to activate it in the config file by setting a positive number of homographies (parameter model->homography_adaptation->num), as is the case in [magic-point_coco_export.yaml](https://github.com/rpautrat/SuperPoint/blob/master/superpoint/configs/magic-point_coco_export.yaml).
