### ISSUE TITLE
export models

### ISSUE THREAD

**Issue by zt-Github-1** [rpautrat/SuperPoint#177]
Hi, 
Sorry to interrupt, I have run through all the steps, and now I want to use the model I trained to perform match_features_demo.py, and I saw the suggestion you gave in other questions, is to use "tf.saved_model.loader.load( sess, [tf.saved_model.tag_constants.SERVING], "./EXPER_DIR/superpoint_coco")" in superpoint/match_feature_demo.py, if this statement is used, "python match_features_demo.py sp_v6 $DATA_PATH/HPatches/i_pool/1.ppm $DATA_PATH/i_pool/6.ppm", what model should be replaced with 'sp_v6'? Do I still need to export my own model? Can you please tell me the export sentence if necessary?

In fact, I use “python export_model.py configs/superpoint_coco.yaml saved_models” to try to export the model, but the error is “ValueError: Checkpoint directory is empty.” But the checkpoint in superpoint_coco file is not empty, or the checkpoint used when exporting the model is not the checkpoint in superpoint_coco file?

By the way, when I executed the step7, the training of 600 times was over to 285 times. Will this affect the output model? because the datasets I used only has 323 images, and the evaluation is still HPatchs, and without modifying the parameters and config.

**Comment by rpautrat** [comment]
Hi,

Yes you need to first export your model. The correct command to export it is `python export_model.py configs/superpoint_coco.yaml <name of your model>`. So you should use the name that you gave to your model, not "saved_models".

Step 7 is an evaluation, not a training. It stops after 285 iterations because there are actually only 285 images in HPatches illumination. So this behavior is perfectly normal. However, if you trained with only 323 images, your model will probably not be very good... SuperPoint requires a lot of images normally, like at least 10,000 I would say.

**Comment by zt-Github-1** [comment]
Thanks for your reply. 

But I have tried the method you said, that is, use my model name as ‘my_models’, and then modify ’‘export_root_dir = Path(EXPER_PATH,'my_models')‘’ in ’export_models‘, and use ‘’python3 export_model.py configs/superpoint_coco.yaml my_models‘’ to  export the model, but the program still reports the same error：
Traceback (most recent call last):
  File "export_model.py", line 35, in <module>
    net.load(str(checkpoint_path))
  File "/home/zt/Desktop/SuperPoint-masterFU(save)/superpoint/models/base_model.py", line 396, in load
    raise ValueError('Checkpoint directory is empty.')
ValueError: Checkpoint directory is empty.

I don’t know why, this is the content in superpoint_coco file:
![Screenshot from 2020-11-13 13-35-48](https://user-images.githubusercontent.com/64679738/99033383-ba4f4e80-25b5-11eb-9848-c3643fc5f104.png)
And,  this is the checkpoint content in superpoint file:
![Screenshot from 2020-11-13 13-34-52](https://user-images.githubusercontent.com/64679738/99033439-d652f000-25b5-11eb-927d-36b744f15d14.png)

**Comment by rpautrat** [comment]
No no, you don't have to change the export_root_dir and you could have kept the previous 'saved_models' this is the OUTPUT folder. What the code require as input is the folder of your model that you train, so 'superpoint_coco' in your case. So the command for you is just:
`python export_model.py configs/superpoint_coco.yaml superpoint_coco`

**Comment by zt-Github-1** [comment]
Oh! Thanks a lot, I have successfully exported the model, but as you said, I used too few training images, so the matching results are not very good. Next I will use more images for another training. Thank you very much for your help!

**Comment by rpautrat** [comment]
Great! Yes you should definitely use more images to train.
I am closing this issue now, feel free to reopen a new one if you have more issues.
