### ISSUE TITLE
version of cudnn

### ISSUE THREAD

**Issue by yakult98** [rpautrat/SuperPoint#179]
I'm sorry to bother you.
I tried to upgrade the version of TF to 1.13, CUDA to 10.0 and cudnn7.6.5 in conda which is defalut.
When I run the step 2,I met the error like that：

`
InvalidArgumentError (see above for traceback): Cannot assign a device for operation magicpoint/pred_tower0/transpose: Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='XLA_CPU'; Tperm in [DT_INT32, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, DT_COMPLEX64, DT_INT64, DT_BOOL, DT_QINT8, DT_QUINT8, DT_QINT32, DT_HALF, DT_UINT32, DT_UINT64]
  device='CPU'; T in [DT_VARIANT]
  device='CPU'; T in [DT_RESOURCE]
  device='CPU'; T in [DT_STRING]
  device='CPU'; T in [DT_BOOL]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT64]
  device='XLA_CPU_JIT'; Tperm in [DT_INT32, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, DT_COMPLEX64, DT_INT64, DT_BOOL, DT_QINT8, DT_QUINT8, DT_QINT32, DT_HALF, DT_UINT32, DT_UINT64]

     [[node magicpoint/pred_tower0/transpose (defined at /home/yakult/SuperPoint/superpoint/models/magic_point.py:30) ]]
`

So how can I solve this problem? Is this related to my version of cudnn?

**Comment by rpautrat** [comment]
Hi, do you have a GPU in your machine? If yes, it is currently not detected by tensorflow, so you might want to check your Nvidia drivers and their compatibility with your CuDnn and Cuda version.

**Comment by yakult98** [comment]
> Hi, do you have a GPU in your machine? If yes, it is currently not detected by tensorflow, so you might want to check your Nvidia drivers and their compatibility with your CuDnn and Cuda version.

Thanks for your answer.
I checked my Nvidia drivers.
![捕获](https://user-images.githubusercontent.com/68220187/99667369-432f2400-2aa7-11eb-8659-4f5035631efe.PNG)
Maybe I should update the CUDA to 10.2?

**Comment by rpautrat** [comment]
Maybe try to follow this configuration: https://github.com/rpautrat/SuperPoint/issues/173#issue-730896838
It has been successfully been used very recently.

**Comment by yakult98** [comment]
> Maybe try to follow this configuration: [#173 (comment)](https://github.com/rpautrat/SuperPoint/issues/173#issue-730896838)
> It has been successfully been used very recently.

I followed this configuration and finished the step 1 successfully,but in step 2, I met the error like [https://github.com/rpautrat/SuperPoint/issues/149](url).So I update the version of tensorflow,CUDA and cudnn.
But now the new problem happened and I don't how to solve it.

**Comment by rpautrat** [comment]
Hum I'm afraid you will have to find the best combination between the GPU driver version, Cuda, CuDnn and Tensorflow by testing a few of them. But it seems that everyone has a different working combination unfortunately...

**Comment by yakult98** [comment]
OK, I will try it. Thanks for your reply.
