### ISSUE TITLE
The number of extracted points

### ISSUE THREAD

**Issue by pixelsmaker** [rpautrat/SuperPoint#180]
Superpoint has two criterions : 300 points for 240*320, 1000 points for 480*640
I have a question that the time of extracting points.
1) extract top-300 points from the points on the each whole image(240*320).
2) extract top-300 points from the points only in the shared view of two images.
I see your code is following the second evaluation strategy, have you ever test the difference of the two strategies? and which strategy do you think was used in the original paper to get the results?

**Comment by rpautrat** [comment]
Hi, no I haven't tested the other approach, and I don't know which strategy was used in the original paper.

But in my opinion the first strategy is a bit unfair as for example for repeatability, the score will not directly reflect the probability for a point of being detected in the other image. It will be lower than the true probability, and will even be lower for pairs of images with small overlap.

**Comment by rpautrat** [comment]
I am closing this now, feel free to reopen it if you still have questions.
