### ISSUE TITLE
About  Synthetic Datasets

### ISSUE THREAD

**Issue by gx0522** [rpautrat/SuperPoint#181]
Hi,
I don't know how to create the synthetic datasets because of my pool python 。 Could you please share the dataset in github。
Thanks

**Comment by rpautrat** [comment]
Hi,
As written in the Readme, if you run the step 1 of the pipeline, the synthetic dataset will be automatically generated. So you just have to run step 1.

**Comment by gx0522** [comment]
Thanks,but when I was trying to run the step1, it showed the error:ModuleNotFoundError: No module named 'superpoint'
![图片](https://user-images.githubusercontent.com/25192298/102158448-70ab9980-3ebc-11eb-9e2e-e621cb5bd197.png)

**Comment by gx0522** [comment]
Hi，
When I was running the step1,there is the error
