### ISSUE TITLE
Unexpected results with pretrained model

### ISSUE THREAD

**Issue by morrisfranken** [rpautrat/SuperPoint#19]
Hello, thank you very much for this repo. Are there examples available for using the pretrained model `pred_magic-point_17-06-2018`? My current attempts produce rather unexpected results on the COCO dataset, where most the interest points seem to be concentrated at the corners.

<img src="https://user-images.githubusercontent.com/6393413/47103563-cbdf9400-d23f-11e8-9d87-619bdcd9b5e9.jpg" alt="drawing" width="320"/> <img src="https://user-images.githubusercontent.com/6393413/47103568-cc782a80-d23f-11e8-87e1-b494b2ad25e7.jpg" alt="drawing" width="320"/>

<img src="https://user-images.githubusercontent.com/6393413/47103565-cc782a80-d23f-11e8-9a5c-d2995fff7146.jpg" alt="drawing" width="320"/> <img src="https://user-images.githubusercontent.com/6393413/47103566-cc782a80-d23f-11e8-9ee0-a10d7bbfd68a.jpg" alt="drawing" width="320"/>

After following the instructions from #18 , removing line 70 `if not ('name' in d):` to include the image on the npz-file, I ran the following command to export the interest points:
```
python3.6 ./superpoint/export_detections.py superpoint/configs/magic-point_coco_export.yaml magic-point_17-06-2018 --export_name pred_magic-point_17-06-2018
```

Lastly I've used this script to visualize the interest-points from the first 5 images from the coco dataset:
```
#!/usr/bin/python3.6
import cv2
import numpy as np
import os
import glob

from superpoint.settings import EXPER_PATH

def draw_keypoints(img, corners, color=(0, 255, 0), radius=3, s=3):
    img = np.repeat(cv2.resize(img, None, fx=s, fy=s)[..., np.newaxis], 3, -1)
    for c in np.stack(corners).T:
        cv2.circle(img, tuple(s*np.flip(c, 0)), radius, color, thickness=-1)
    return img
    
def select_top_k(prob, thresh=0, num=300):    
    pts = np.where(prob > thresh)
    idx = np.argsort(prob[pts])[::-1][:num]
    pts = (pts[0][idx], pts[1][idx])
    return pts
    
experiment = 'pred_magic-point_17-06-2018'
files = glob.glob("{}/*.npz".format(os.path.join(EXPER_PATH, "outputs", experiment)))

for i, path in enumerate(files[:5]):
    d = np.load(path)
    points1 = select_top_k(d['prob'], thresh=0)
    im1 = draw_keypoints(d['image'][..., 0], points1, (0, 255, 0))
    cv2.imwrite("interest_points_{}.png".format(i), im1)
```

But the interest points seem to be completely off. What am I doing wrong here?

**Comment by rpautrat** [comment]
The problem was probably in the normalization of the input image. I just released a new pretrained model that should work on images normalized between 0 and 1. Feel free to use it if you still need to (because I answer a bit late...).
