### ISSUE TITLE
Different input shapes for superpoint

### ISSUE THREAD

**Issue by dongyangcai** [rpautrat/SuperPoint#192]
Hi
   I found that on training stage, the input shape of image(coco) is 240*320, but during inference, the input shape of superpoint is 480*640,  would you tell me why the shape is different and how it works? thanks!

**Comment by rpautrat** [comment]
Hi, it is a fully convolutional architecture, so the image size does not really matter. You can train with one size and evaluate with another. The main thing is the scale of the patch description that would change.

In this repo, we followed the practice of the original authors, with a descriptor evaluation on 480x640 images to have more details in the description. But you can of course use it with other resolutions.

**Comment by dongyangcai** [comment]
got it, thank you very much for your explanation!

**Comment by dongyangcai** [comment]
Hi, I got another problem when inference on my own dataset. I trained model with 240x320s, then i inference the model with 240x320s and 480x640s. however, the result shows 240x320s input performs bad.
do you have any idea if I want to detect more points(or if I want to improve the accuracy of feature point's location) on a small size input (like 240x320s)? thanks

**Comment by rpautrat** [comment]
Hi, do you have example images between 240x320 and 480x640 inferences?
To increase the number of detections, you can decrease the 'detection_threshold' in the config file at inference time, and increase the 'top_k' parameter.

**Comment by dongyangcai** [comment]
![Uploading 240.png…]()

240x320

![Uploading 480.png…]()

480x640

**Comment by dongyangcai** [comment]
![240](https://user-images.githubusercontent.com/31368434/111434023-019f4480-873a-11eb-975d-7a2b657b2527.png)
240x320
![480](https://user-images.githubusercontent.com/31368434/111434062-1085f700-873a-11eb-8d4a-622ef075a4d9.png)
480x640

**Comment by rpautrat** [comment]
So is there a big difference? The 240x320 seems reasonable to me. You can play with the top_k parameter and detection_threshold to get more/less points, but overall it seems like a normal output.

**Comment by dongyangcai** [comment]
![240](https://user-images.githubusercontent.com/31368434/111436726-3eb90600-873d-11eb-9e39-8692c9889cc3.png)
It seems that feature points cannot be detected in some areas in 240x320 inputs

**Comment by rpautrat** [comment]
True, but there is technically nothing interesting in this area. Remember that SuperPoint is a corner detector, so no corner = no point. But you can force it to detect more points with a lower detection_threshold, and it will eventually detect points in this area as well. Those points will be quite uncertain though.

**Comment by dongyangcai** [comment]
got it, thank you for your advice!
