### ISSUE TITLE
No module named superpoint.datasets 

### ISSUE THREAD

**Issue by JayasaiK** [rpautrat/SuperPoint#195]
![Capture](https://user-images.githubusercontent.com/65283616/109879597-a5f99500-7c2a-11eb-9116-f97759a771d0.JPG)
Hi, I'm having a problem while running the first command, please check the following error.

**Comment by rpautrat** [comment]
Hi, why are you using for 'sudo' for this command? This should not be necessary.
Did you first follow the installation instruction `make install`?

**Comment by JayasaiK** [comment]
Thank you for your help it is resolved now.
now I have trouble with this.

(spnw) smart1@smart1:~/Desktop/SuperPoint-master/superpoint$ python experiment.py train configs/magic-point_shapes.yaml magic-point_synth
/home/smart1/anaconda3/envs/spnw/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/smart1/anaconda3/envs/spnw/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/smart1/anaconda3/envs/spnw/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/smart1/anaconda3/envs/spnw/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/smart1/anaconda3/envs/spnw/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/smart1/anaconda3/envs/spnw/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
experiment.py:157: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[03/05/2021 17:31:12 INFO] Running command TRAIN
Traceback (most recent call last):
  File "experiment.py", line 164, in <module>
    args.func(config, output_dir, args)
  File "experiment.py", line 101, in _cli_train
    train(config, config['train_iter'], output_dir, pretrained_dir)
  File "experiment.py", line 26, in train
    with _init_graph(config) as net:
  File "/home/smart1/anaconda3/envs/spnw/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "experiment.py", line 72, in _init_graph
    n_gpus = get_num_gpus()
  File "experiment.py", line 66, in get_num_gpus
    return len(os.environ['CUDA_VISIBLE_DEVICES'].split(','))
  File "/home/smart1/anaconda3/envs/spnw/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VISIBLE_DEVICES'

**Comment by rpautrat** [comment]
Hi, do you have an Nvidia GPU with the correct drivers and Cuda installed on your computer? It seems that the code doesn't find any of them.

**Comment by JayasaiK** [comment]
Yes, I have titan xp gpu. I think everything is installed properly, can you please check?

(spnw) smart1@smart1:~/Desktop/SuperPoint-master/superpoint$ which nvcc
/usr/local/cuda/bin/nvcc
(spnw) smart1@smart1:~/Desktop/SuperPoint-master/superpoint$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
(spnw) smart1@smart1:~/Desktop/SuperPoint-master/superpoint$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  410.78  Sat Nov 10 22:09:04 CST 2018
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
(spnw) smart1@smart1:~/Desktop/SuperPoint-master/superpoint$ 
(spnw) smart1@smart1:~/Desktop/SuperPoint-master/superpoint$ nvidia-smi
Tue Mar  9 14:17:01 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN Xp            Off  | 00000000:01:00.0  On |                  N/A |
| 23%   34C    P8    13W / 250W |    348MiB / 12194MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       965      G   /usr/lib/xorg/Xorg                           163MiB |
|    0      1462      G   compiz                                       141MiB |
|    0      8090      G   /usr/lib/firefox/firefox                       3MiB |
|    0     32740      G   /opt/teamviewer/tv_bin/TeamViewer             36MiB |

**Comment by JayasaiK** [comment]
![image](https://user-images.githubusercontent.com/65283616/110539768-82c35f80-80da-11eb-8ccb-56741b6a90b1.png)

**Comment by rpautrat** [comment]
Yes, it seems correctly installed. Make sure that you have installed tensorflow_gpu as well.

The problem might also come from a wrong combination between your driver, CUDA, CuDNN and Tensorflow versions. You should check online that they are correct.

This a problem related to your computer configuration otherwise, so I cannot bring you support there. You should rather check forums with questions about Tensorflow and why it cannot recognize your GPU.

**Comment by rpautrat** [comment]
I am closing this now as it is a hardware issue and I can't help more than that. I hope you solved your issue.
