### ISSUE TITLE
output size mismatch

### ISSUE THREAD

**Issue by FENGChenxi0823** [rpautrat/SuperPoint#203]
Hey @rpautrat , thanks for your great work! I am trying to detect my image with size of [604,960]. The output heatmap and descriptors by net.predict is [608,964]. Is that because of 2 padding on the border? How should I interpret the indices of heatmap to points in image? Any offset needed?

**Comment by rpautrat** [comment]
Hi, by construction SuperPoint only works for images whose size is a multiple of 8 (because it considers 8x8 patches). So I recommend to crop/resize your image to fit this requirement before running SuperPoint on it.

**Comment by FENGChenxi0823** [comment]
Great point, I will try that. Thanks a lot!

**Comment by FENGChenxi0823** [comment]
I tried the image size 1208*1960. It turns out the keypoints are shifted/scaled a bit. Do you have any suggestions on this? 
![5000_00_05001](https://user-images.githubusercontent.com/29789927/115076747-d97a4100-9eb1-11eb-936d-54232b10b80b.jpg)

**Comment by rpautrat** [comment]
That's strange indeed, it seems that all the keypoints are slightly shifted to the right.
Why did you choose the scale 1208*1960 actually? Doubling your original size should give 1208*1920, not 1960. If you chose the wrong size, this might explain the offset in the width direction.

**Comment by FENGChenxi0823** [comment]
That was a mistake. Thank you for pointing it out! It solved the shift problem.
I noticed that with 1 GPU, the inference results a good. If i expand the GPU number to 2 or more, it starts to have problems.

**Comment by rpautrat** [comment]
What kind of problems? In my experience, it was still fine with 2 GPUs, but bugs started to appear from 3 GPUs.

**Comment by FENGChenxi0823** [comment]
Sorry for my late reply. With 2GPU,some pictures look good but some fail. Here is an example of a bad result
![5000_00_00503](https://user-images.githubusercontent.com/29789927/121307558-f67d3000-c8b4-11eb-996a-e7585ac633a0.jpg)

**Comment by rpautrat** [comment]
Interesting, this might be due to the way the output tensors are gathered back after splitting them across different GPUs. I won't have time to look into this issue right now, so I suggest to only use one GPU for inference for now.

**Comment by FENGChenxi0823** [comment]
Thanks for your help!
