### ISSUE TITLE
Can SuperPoint handle images with 2 channels?

### ISSUE THREAD

**Issue by LulinZhang** [rpautrat/SuperPoint#205]
Hi, @rpautrat , I guess SuperPoint extract keypoints based on gray images (one channel)?
Is it possible for SuperPoint to handle images with 2 channels (for example gray-scale + depth) or 3 channels (RGB) without converting to gray images?

**Comment by rpautrat** [comment]
Hi, yes the current SuperPoint works with grayscale images. But it would be quite easy to retrain it for 2 or 3 channel images.

I think you would need only three changes in the code for that:
- change the dataloader to yield the images you want.
- in `models/magic_point.py` and `models/super_point.py`, change the input_spec to 2 or 3 channels:
https://github.com/rpautrat/SuperPoint/blob/313a0a115961bc2a98a5ed1d7bde33fa99542398/superpoint/models/magic_point.py#L11
- update the functions warping images (in the [homography augmentation](https://github.com/rpautrat/SuperPoint/blob/313a0a115961bc2a98a5ed1d7bde33fa99542398/superpoint/datasets/utils/pipeline.py#L40) and [homography adaptation](https://github.com/rpautrat/SuperPoint/blob/313a0a115961bc2a98a5ed1d7bde33fa99542398/superpoint/models/homographies.py#L28)) to handle 2 or 3 channels.
