### ISSUE TITLE
Evaluation metrics for descriptors

### ISSUE THREAD

**Issue by reacher-l** [rpautrat/SuperPoint#208]
Hello, may I ask if the evaluation of descriptor NNmap and Matching score is included in this code

**Comment by rpautrat** [comment]
Hi, no it has not been included in this code so far. But it should not be too hard to re-implement it normally.

**Comment by reacher-l** [comment]
Thank you. In order to make a fair comparison, I would like to ask whether this indicator can be open source

**Comment by rpautrat** [comment]
Note that this repo is not the original code for SuperPoint, so if you want a comparison to the original paper you should use the [original repo](https://github.com/magicleap/SuperPointPretrainedNetwork).

I have never implemented these metrics personally, and they are not open sourced in the original repo either. So the best for you would be to re-implement them yourself and ask details about their implementation to the original authors if you want to make it as fair as possible.

**Comment by reacher-l** [comment]
Thank you very much and look forward to your more work on registration.
