### ISSUE TITLE
Questions about the "correct distance"

### ISSUE THREAD

**Issue by 07hyx06** [rpautrat/SuperPoint#209]
Hi! In the Suppl. Section A, says

>  we use a threshold ε to determine if a returned point location x is correct relative to a set of K ground-truth corners {ˆx1, . . . , ˆxK}.

Is the ground truth corner be the center of the patch provided by the HPatches dataset? The HPatches paper says that there are almost 1k patches per image, which means for each image, there are almost 1k ground truth corners?

**Comment by rpautrat** [comment]
Hi!

No, the patches of HPatches are not used in the evaluation, only the full images. The corner detection average precision is only used with the synthetic dataset to evaluate the accuracy of the pretrained MagicPoint, where ground truth corners are known. On real images such as the HPatches ones, there is no ground truth point, so we cannot compute the mAP.

**Comment by 07hyx06** [comment]
Got it. Thanks.
