### ISSUE TITLE
No module named 'superpoint.settings' on Windows 10

### ISSUE THREAD

**Issue by NoRealLogin** [rpautrat/SuperPoint#210]
Hello, 

I checked the other topics with similar looking problems but none resolved mine. I work on Windows 10 so I install make command via Chocolatey then I ran `make install` like you advise us to. But when I try to run the command: `python experiment.py train configs/magic-point_shapes.yaml magic-point_synth` I got this issue : 

![image](https://user-images.githubusercontent.com/35778875/118444998-28540a00-b6ee-11eb-97ba-a4d8100ebbf3.png)

After looking the `make install` run more closely I can see : 

![image](https://user-images.githubusercontent.com/35778875/118445165-5f2a2000-b6ee-11eb-814f-2cf628f648fa.png)

The penultimate line means : "The specified file can not be found"

I hope you can help me,

Thanks for your works.

**Comment by rpautrat** [comment]
Hi,

Sorry I have no experience of running Python on Windows, so I cannot help you there... All the instructions here were tested on Linux only. You could try to install another python package locally with a `setup.py` file as in this repo to see if you get the same error. If yes, it is probably that installing the package in Windows has to be done differently.

**Comment by NoRealLogin** [comment]
Thanks for reply, I kinda new to python on windows so I'll test some things then see. I'll may try to run it through WSL 2.

**Comment by Arka161** [comment]
You don't need WSL, you can hardcode a custom directory in the code and get it working without the `EXPER_PATH` parameter. 
For example, you could do something like: 

```
    weights_root_dir = Path("", 'saved_models')
    weights_root_dir.mkdir(parents=True, exist_ok=True)
    weights_dir = Path(weights_root_dir, weights_name)
```

This is assuming you have the saved_models folder in the SuperPoint/superpoint directory.
