### ISSUE TITLE
No module named 'superpoint'

### ISSUE THREAD

**Issue by JuntingLee** [rpautrat/SuperPoint#214]
Hi. Rpautrat
I run the first step in the folder superpoint : python experiment.py train configs/magic-point_shapes.yaml magic-point_synth
but I get :
Traceback (most recent call last):
  File "experiment.py", line 9, in <module>
    from superpoint.datasets import get_dataset
ModuleNotFoundError: No module named 'superpoint'

**Comment by rpautrat** [comment]
Hi, did you run the install command of the Readme, `make install`?

**Comment by JuntingLee** [comment]
Yes,and I provide the path:
`sh setup.sh
Path of the directory where datasets are stored and read: /gfsdata01/data
Path of the directory where experiments data (logs, checkpoints, configs) are written: /gfsdata01/result`

> Hi, did you run the install command of the Readme, `make install`?

**Comment by rpautrat** [comment]
And there is no error message?

Are you using anaconda? If yes, you can try to run `conda install pip` before running the `make install` command.

**Comment by JuntingLee** [comment]
Yes, I am using anaconda. Thanks!

> And there is no error message?
> 
> Are you using anaconda? If yes, you can try to run `conda install pip` before running the `make install` command.
