### ISSUE TITLE
GPU slower than CPU

### ISSUE THREAD

**Issue by okatsuka** [rpautrat/SuperPoint#215]
I run matche_features_demo.py by pretrained models sp_v6 on Docker.

However, process time with GPU is slower than CPU.

I calculate process time as follows.
```
start = time.time()
        
out1 = sess.run([output_prob_nms_tensor, output_desc_tensors],
                        feed_dict={input_img_tensor: np.expand_dims(img1, 0)})
end = time.time()
proces_time = end - start
```
Process time
GPU：1ms
CPU：0.3ms

Why running with GPU is slow?

| OS | Ubuntu 18.04 on Docker |
| ------------- | ------------- |
| CPU | Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz |
| GPU | GeForce RTX 2080 SUPER |

**Comment by rpautrat** [comment]
Hi, that is an interesting comparison, I had not tried it myself. For a single image at a time and a very good CPU like you have, this can make sense I think. The GPU version probably loses a lot of time transferring data from CPU to GPU.

But I guess that if you run it on batched images (e.g. 10 images at a time), the GPU version will eventually become faster.

**Comment by okatsuka** [comment]
Thank you for your reply.
I understand that the GPU version takes a long time to transfer.
On the other hand, the Pytorch version of Magic leap is running pretty fast on GPU.
Why is the tensorflow version slow?
Is there a way to get it to run faster on the GPU version?

**Comment by rpautrat** [comment]
Yes, this code is not super optimized for fast inference and could definitely be improved. You can have a look at this issue to get ideas on how to improve the efficiency: https://github.com/rpautrat/SuperPoint/issues/109.
