### ISSUE TITLE
How well would this work when color scheme changes

### ISSUE THREAD

**Issue by kafan1986** [rpautrat/SuperPoint#217]
I have a use case where I need to recognize certain part of an image. Now the source of this data for example is like a screenshot of a website. Now I can create a database of all the key points and corresponding descriptors and store it in a DB and use it to match at a later stage. Now the problem is during matching a user might change theme of a website, thus the color scheme might get changed. So can this work well in such scenario? I just wanted to ask someone having experience in this?

**Comment by rpautrat** [comment]
Hi, so the layout would be fixed, but the color scheme could change if I understood correctly?

I think that the keypoint+descriptors approach could work indeed. I am not sure if the pretrained model would work out of the box though. You can try and see how it performs, but you might need to fine-tune it on your website images with different colors between two images for better performance.

**Comment by kafan1986** [comment]
> Hi, so the layout would be fixed, but the color scheme could change if I understood correctly?
> 
> I think that the keypoint+descriptors approach could work indeed. I am not sure if the pretrained model would work out of the box though. You can try and see how it performs, but you might need to fine-tune it on your website images with different colors between two images for better performance.

Yes, the layout will remain same but the colour scheme will change. Also, maybe little bit of aspect ratio change depending on zoom and viewport changes; also maybe due to language changes the text on the web elements might change.

Regarding the training. I believe this implementation auto creates training data (unsupervised) from set of single images. How can I create the training data then? Do I need to modify that part of the code and pass rather two set of images taken with exact same dimension and same viewport, just with colour theme changed?

Also, I haven't looked at the code in this repo. Does this expect only grayscale images like SIFT and ORB or does this expect RGB images?

**Comment by rpautrat** [comment]
Hi,

You need to create a new dataloader file in the datasets folder for your new dataset. It can take two images as input, with same viewpoint and colour theme changed. You can use `patches_dataset.py` as inspiration for that. You can then add the viewpoint augmentation to the second image during the preprocessing to make it robust to viewpoint changes (using https://github.com/rpautrat/SuperPoint/blob/313a0a115961bc2a98a5ed1d7bde33fa99542398/superpoint/datasets/utils/pipeline.py#L40).

The current code expect grayscale images as input, renormalized between 0 and 1.
