### ISSUE TITLE
Question regarding the homographic augmentation

### ISSUE THREAD

**Issue by hichem-abdellali** [rpautrat/SuperPoint#220]
Hi, 

I would like to kindly ask if there is a possibility to avoid the black region (0 paddings) when we apply the Homography? I checked the parameters but didn't succeed to find a good combination

Thank you

**Comment by rpautrat** [comment]
Hi,
You can restrain the homographies to prevent them from creating black regions by setting the parameter 'allow_artifacts' to false in the training config file (data->augmentation->homographic->params->allow_artifacts).
However this will greatly reduce the diversity of homographies that you can achieve.
