### ISSUE TITLE
optimizer ArithmeticOptimizer

### ISSUE THREAD

**Issue by 1962975362** [rpautrat/SuperPoint#221]
when I train the model, it shows "Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node magicpoint/train_tower0/strided_slice_2. Error: ValidateStridedSliceOp returned partial shapes [64,?,?] and [64,?,?,1]"

It can continue to train, but does this warning have an impact, and are there any solutions

**Comment by rpautrat** [comment]
Hi,
I have never seen this error. What version of Tensorflow are you using?

**Comment by rpautrat** [comment]
This code was tested successfully with TF 1.12, so you could maybe downgrade your TF version to solve the previous issue.

Your new issue seems to be related to pathlib, which did not list the folders of your HPatches dataset. You can check that you are using the latest version of the python package pathlib. You can also check the output of the following line:
https://github.com/rpautrat/SuperPoint/blob/313a0a115961bc2a98a5ed1d7bde33fa99542398/superpoint/datasets/patches_dataset.py#L26
and see if it manages to find the folder of the HPatches scenes or not.

**Comment by rpautrat** [comment]
I am closing this for now, feel free to reopen it if necessary.

**Comment by johnren-code** [comment]
> when I train the model, it shows "Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node magicpoint/train_tower0/strided_slice_2. Error: ValidateStridedSliceOp returned partial shapes [64,?,?] and [64,?,?,1]"
> 
> It can continue to train, but does this warning have an impact, and are there any solutions

i met this problem also,have you solved this?
