### ISSUE TITLE
Whether it works on scaled images?

### ISSUE THREAD

**Issue by GopinathCool** [rpautrat/SuperPoint#226]
Hi, 

Thanks for this wonderful project, I have a requirment to find the K nearest neigbours for the given image.
I am current using resnet50 pretrained model to extract image features. But I did not perform well, when the same image is stretched and zoomed.

Whether the SuperPoint will solve this case?

**Comment by rpautrat** [comment]
Hi,

In theory you could try to use SuperPoint to solve this task, but I don't know if it will yield better results than your current method.

One possibility would be to apply NetVLAD on top of SuperPoint features to extract image features that are less sensitive to stretching and zooming. Or you could directly match SuperPoint features between your query image and the database images (with some filtering with RANSAC), and come up with a metric to rank the matched images (e.g. number of inliers).
