### ISSUE TITLE
KeyError: "The name 'superpoint/image:0' refers to a Tensor which does not exist.

### ISSUE THREAD

**Issue by lhf981128** [rpautrat/SuperPoint#228]
Hello!

I personally realized the training of magic point and obtained the corresponding model weights. Instead of continuing the training of super point, I directly used the obtained weight to run “match_features_demo.py”,but the following errors occurred：
Traceback (most recent call last):
  File "match_features_demo.py", line 118, in <module>
    input_img_tensor = graph.get_tensor_by_name('superpoint/image:0')
  File "C:\Users\Administrator\Anaconda3\envs\mytensorflow\lib\site-packages\tensorflow\python\framew                                                  ork\ops.py", line 3666, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "C:\Users\Administrator\Anaconda3\envs\mytensorflow\lib\site-packages\tensorflow\python\framew                                                  ork\ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\Users\Administrator\Anaconda3\envs\mytensorflow\lib\site-packages\tensorflow\python\framew                                                  ork\ops.py", line 3532, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'superpoint/image:0' refers to a Tensor which does not exist. The operation, 'sup                                                  erpoint/image', does not exist in the graph."
 I would like to ask why such a mistake occurred? Do I have to complete all the steps listed in order to get the correct model and weights?I just run to the third step to export the model and get the corresponding “.pb”file
What differences have between the model Igot and the model "sp_v6" in pretrained models that you provided? 
Looking forward to your reply, thank you very much！
@rpautrat

**Comment by rpautrat** [comment]
Hi, you cannot run `match_features_demo.py` with MagicPoint, since it has no descriptors. MagicPoint and SuperPoint are different networks and cannot be interchanged like this.

If you still want to run the inference of MagicPoint only, you can change the following lines:
```
        input_img_tensor = graph.get_tensor_by_name('superpoint/image:0')
        output_prob_nms_tensor = graph.get_tensor_by_name('superpoint/prob_nms:0')
        output_desc_tensors = graph.get_tensor_by_name('superpoint/descriptors:0')
```
into
```
        input_img_tensor = graph.get_tensor_by_name('magicpoint/image:0')
        output_prob_nms_tensor = graph.get_tensor_by_name('magicpoint/prob_nms:0')
```
and adapt the rest of the script to ignore the matching part (which would require the descriptors of SuperPoint).

**Comment by lhf981128** [comment]
> Hi, you cannot run `match_features_demo.py` with MagicPoint, since it has no descriptors. MagicPoint and SuperPoint are different networks and cannot be interchanged like this.
> 
> If you still want to run the inference of MagicPoint only, you can change the following lines:
> 
> ```
>         input_img_tensor = graph.get_tensor_by_name('superpoint/image:0')
>         output_prob_nms_tensor = graph.get_tensor_by_name('superpoint/prob_nms:0')
>         output_desc_tensors = graph.get_tensor_by_name('superpoint/descriptors:0')
> ```
> 
> into
> 
> ```
>         input_img_tensor = graph.get_tensor_by_name('magicpoint/image:0')
>         output_prob_nms_tensor = graph.get_tensor_by_name('magicpoint/prob_nms:0')
> ```
> 
> and adapt the rest of the script to ignore the matching part (which would require the descriptors of SuperPoint).

OK, thank you very much for taking the time to reply to me. I'll try it as you say
Thank you！
