### ISSUE TITLE
ValueError: Shape must be rank 2 but is rank 0 for 'matmul_1' (op: 'MatMul') with input shapes: [3,3], [].

### ISSUE THREAD

**Issue by lhf981128** [rpautrat/SuperPoint#229]
Sorry to bother you again. After listening to your comments yesterday, I ran the following steps, but when I ran to  “python export_descriptors.py configs/superpoint_hpatches.yaml superpoint_coco --export_name=superpoint_hpatches-v”，a code in "patches_dataset.py" reported the following error :
ValueError: Shape must be rank 2 but is rank 0 for 'matmul_1' (op: 'MatMul') with input shapes: [3,3], [].

I have generated patches in dir"COCO/patches",and there is no problem reading the data,Iwant to ask why this error happended
Looking forward to you reply, thank you very much.
![1](https://user-images.githubusercontent.com/62584470/129181087-5b64e632-03d5-4811-8977-b1eae3f28ece.png)
@rpautrat

**Comment by rpautrat** [comment]
Hi,

Could you double-check that the patches dataset has been correctly generated and that the homographies are correctly read in the dataloader? Because from your error message, I suspect that your homographies might be empty...

**Comment by rpautrat** [comment]
I am closing this now, feel free to reopen it if necessary.
