### ISSUE TITLE
Could not find opencv-python-contrib, there may be an error in the contents of requirements.txt?

### ISSUE THREAD

**Issue by KNLc** [rpautrat/SuperPoint#23]
hello, I encounter a error when I install the required dependency through type: pipe install -r requirement.txt. The error display : Could not find a version that satisfies the requirement opencv-python-contrib (from versions: )  No matching distribution found for `opencv-python-contrib`.

Then, I tried to install opencv-python-contrib by type: `pip install opencv-contrib-python`, and the installation is successful. But the `requirements.txt` is written `opencv-python-contrib` instead of `opencv-contrib-python`, so I guess the requirements.txt is wrong here. 
Is that right?

**Comment by rpautrat** [comment]
Good catch, thanks for correcting the typo!
