### ISSUE TITLE
KeyError: "The name 'image:0' refers to a Tensor which does not exist. The operation, 'image', does not exist in the graph."

### ISSUE THREAD

**Issue by lhf981128** [rpautrat/SuperPoint#230]
Hello, I have exported my own model and used it to run “match_features_demmo.py”,but the following error happended:

KeyError: "The name 'image:0' refers to a Tensor which does not exist. The operation, 'image', does not exist in the graph."

Can you help me solve this problem？Thank you very much.
Looking forward to your reply.
@rpautrat 
![1](https://user-images.githubusercontent.com/62584470/129347243-ffb23f27-4a19-4a1a-abb5-4cac9a6b3b58.png)

**Comment by rpautrat** [comment]
Hi, this is related to your other issue https://github.com/rpautrat/SuperPoint/issues/228, and I told you to replace 'superpoint' by 'magicpoint', not to remove it completely.
