### ISSUE TITLE
Output size bigger than input size?

### ISSUE THREAD

**Issue by B-Meg** [rpautrat/SuperPoint#232]
Hey!
So my input data has the size: (1, 200, 300, 1)
And the output data of the superpoint nn with the trained weight sp_v6 has the size (1, 200, 304)
Why? What is happening here? I assumed that SuperPoints gives me as an result the probability of every pixel for being a keypoint? So how comes that I receive more pixels back?

**Comment by rpautrat** [comment]
Mmmh of you do this, all your detections will probably be translated by a subpixel factor compared to their true position, so it is not ideal if you want accurate detections. I think it is better to first cut your image to size (200, 296), and then run SuperPoint.
