### ISSUE TITLE
Problem in training……

### ISSUE THREAD

**Issue by qdtdl** [rpautrat/SuperPoint#238]
running the command line
python3 experiment.py train configs/magic-point_shapes.yaml magic-point_synth
There is too much：Segmentation fault (core dumped)，Check failed: h != kInvalidChunkHandle
Sometimes, when executed under the same conditions, the error reports are different.
What's my problem?

**Comment by qdtdl** [comment]
With your help, I finally got the model I need. Thank you very much for your reply

**Comment by GoroYeh-HRI** [comment]
> I finished the training according to your suggestion. Thank you very much.

Hi @qdtdl , may I ask did you get training error where the loss & precision are both nan, and recall 0.0000?
I also followed #173  but got this training issue.

![image](https://github.com/user-attachments/assets/7164fc2b-ab1a-449f-803c-c9f15934620a)

**Comment by heroamd** [comment]
I think you met no CUDA_VISIBLE_DEVICE varible before, you change ./superpoint/utils/experiments.py line:62.
Make sure your CUDA_VISIBLE_DEVICE number suit to you actually can run model GPUs number .
