### ISSUE TITLE
Pixel coordinates from feature extractor

### ISSUE THREAD

**Issue by rishabhramteke** [rpautrat/SuperPoint#242]
How can I get the pixel coordinates from the keypoints or descriptors obtained from the superpoint feature extractor?

**Comment by rpautrat** [comment]
Hi, check this out: https://github.com/rpautrat/SuperPoint/blob/313a0a115961bc2a98a5ed1d7bde33fa99542398/superpoint/match_features_demo.py#L19
This code is only extracting integer keypoints though, but you can remove the cast to integers, and use [torch.nn.functional.grid_sample](https://pytorch.org/docs/stable/generated/torch.nn.functional.grid_sample.html) to extract the descriptors from float keypoints.
