### ISSUE TITLE
Problem in step 2 when Exporting detections on MS-COCO

### ISSUE THREAD

**Issue by FeiXie8** [rpautrat/SuperPoint#243]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation magicpoint/pred_tower1/transpose: node magicpoint/pred_tower1/transpose (defined at /home/xiefei/pyenv/tf1/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748)  was explicitly assigned to /device:GPU:1 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:GPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0 ]. Make sure the device specification refers to a valid device

**Comment by liyaoshun** [comment]
换tf版本就好了，换到2.0一下。同时将cuda换到10
