### ISSUE TITLE
I Can Only Exporting detections on MS-COCO trainning dataset

### ISSUE THREAD

**Issue by FeiXie8** [rpautrat/SuperPoint#246]
though the code is ' test_set = dataset.get_test_set() ',the npz file i got is npz on tranning dataset

**Comment by rpautrat** [comment]
Hi, the code is using 'test_set = dataset.get_test_set()' to turn off the training options (we don't need them when exporting the pseudo ground truth).

This repo is only using COCO for training, so you cannot use it to export detections on the COCO test set. If you really want to do so, you can change the line https://github.com/rpautrat/SuperPoint/blob/313a0a115961bc2a98a5ed1d7bde33fa99542398/superpoint/datasets/coco.py#L41 with 'COCO/test2014'.

**Comment by FeiXie8** [comment]
> Hi, the code is using 'test_set = dataset.get_test_set()' to turn off the training options (we don't need them when exporting the pseudo ground truth).
> 
> This repo is only using COCO for training, so you cannot use it to export detections on the COCO test set. If you really want to do so, you can change the line
> 
> https://github.com/rpautrat/SuperPoint/blob/313a0a115961bc2a98a5ed1d7bde33fa99542398/superpoint/datasets/coco.py#L41
> with 'COCO/test2014'.

Tks very much
