### ISSUE TITLE
KeyError: 'TMPDIR'

### ISSUE THREAD

**Issue by jinjingyi** [rpautrat/SuperPoint#25]
Hello! when I run the first command, a strange error happened as following. Can you tell me why ? Thank you very much !!!
![image](https://user-images.githubusercontent.com/33051720/49942306-e96b6a00-ff1f-11e8-8c64-4428471f0d8f.png)

**Comment by rpautrat** [comment]
Hello! This problem has already happened to others apparently and you can fix it by following this advice: https://github.com/rpautrat/SuperPoint/issues/21#issuecomment-443630987

**Comment by jinjingyi** [comment]
@rpautrat  wow, I got it, thanks.
