### ISSUE TITLE
KeyError: 'warped_image'

### ISSUE THREAD

**Issue by Joshpk29** [rpautrat/SuperPoint#269]
Sorry if this ha been asked already but I'm having some issues when I try to run export_descriptor for my custom dataset. I keep  getting this error:

Traceback (most recent call last):
  File "export.py", line 410, in <module>
    args.func(config, output_dir, args)
  File "export.py", line 125, in export_descriptor
    img_0, img_1 = sample["image"], sample["warped_image"]
KeyError: 'warped_image'

Has anyone encountered this and knows how to fix it --

**Comment by rpautrat** [comment]
Hi, does your custom dataset actually implements a "warped_image"?

**Comment by Joshpk29** [comment]
I think so -- I essentially copied the COCO.py file and modified the file paths to be my dataset, then in the default config at the top of the file I changed warped_pair to be enabled
![image](https://user-images.githubusercontent.com/44280379/193836282-48e11091-7661-4811-8aba-5ed4d8235eea.png)

**Comment by Joshpk29** [comment]
sorry closed on accident

**Comment by Joshpk29** [comment]
I did also generate the patches for my dataset -- so I have a LOL/patches folder with folder 0-15 each has 1.jpg, 2.jpg and H_1_2 file, if i could find a way use these in export that would be good too

**Comment by Joshpk29** [comment]
figured out my error in loader.py line 114 change the if statement from just hpatches to hpatches or 'custom_dataset_name'
