### ISSUE TITLE
About illumination change problem

### ISSUE THREAD

**Issue by LSK0821** [rpautrat/SuperPoint#281]
Using superpoint demo to try to run one dataset of illumination changes in HPatchs, the number of feature points extracted is not consistent, have you considered solving this problem? And what do the blue lines that appear in the image represent?
![frame_00002](https://user-images.githubusercontent.com/69196380/205443766-a6ffe500-b5df-4527-ad1c-a7ead858aafc.png)
![frame_00005](https://user-images.githubusercontent.com/69196380/205443770-f7e6bb8d-9296-4508-a851-2a3f09f975a6.png)

**Comment by rpautrat** [comment]
Hi, if you want to keep the same number of keypoints extracted in the two images, you can use the parameter `--k_best` (it should be 1000 by default).

The code is supposed to draw point matches between the two images. In your case, it seems it is wrongly drawing lines inside the same image. Did you modify the demo file somehow?

**Comment by LSK0821** [comment]
Dear author, hello, thank you very much for receiving your reply. I have read it and have the following doubts. 
First, I used a demo of the superpoint pre-training model and didn't change any parameters. Then, use this demo to extract the features of the two images respectively. What I show is the feature extraction results of the two images, not the feature matching results.
I have two doubts. First, the blue line in the result graph of feature extraction was drawn by demo. Do you know this meaning? The gif shown by the original author also exists with this blue line as follows.
![processed_kitti](https://user-images.githubusercontent.com/69196380/205479454-4dc3e476-80ee-45fc-940e-d01b6c1d2705.gif)
![processed_icl](https://user-images.githubusercontent.com/69196380/205479484-7fd13089-ee5a-4c66-b679-0820d4c2ecd0.gif)
Second, I want to ask why the number of extracted features is different in the same scene and the same feature extraction Settings, only the illumination changes? Has it ever been considered that before the superpoint network is trained, more label data under different lighting is used for training, and whether the final model will be more robust to lighting changes?

**Comment by rpautrat** [comment]
Hi, ok, I did not understand that you were referring to the demo of the pre-trained model. Then why do you ask the question on this repo?

But it is easy to answer, the colored lines are representing the tracking of keypoints between multiple frames. Each line is the trajectory of one keypoint.

This method is of course not perfect, so you cannot expect to detect exactly the same keypoints with illumination changes between the same image. It is robust to it until a certain point, as it was trained with synthetic augmentation such as random exposure, brightness, shadows. People have also tried adding more lighting changes during training, this can make the network a little more robust to these changes. But it will never be perfect.

**Comment by LSK0821** [comment]
OK! Thank you very much for your reply!
