### ISSUE TITLE
from superpoint.settings import EXPER_PATH

### ISSUE THREAD

**Issue by yyyyiiiinnnn** [rpautrat/SuperPoint#297]
An error occurred：Cannot find reference 'settings' in '__init__.py'

**Comment by rpautrat** [comment]
Hi, did you run the installation instructions: `make install`?

**Comment by yyyyiiiinnnn** [comment]
> 

Do you mean to install those libraries in requirements.txt? If yes then I installed.Thanks for your replying!

**Comment by yyyyiiiinnnn** [comment]
If I create a $EXPER_PATH file under the "superpoint" path, should "from superpoint.settings import EXPER_PATH" be changed to "from superpoint import EXPER_PATH".Looking forward to your reply！

**Comment by yyyyiiiinnnn** [comment]
I think maybe my problem is that there is no "setting.py" file and my "_init_.py" file is empty.but i don't kown how to solve.

**Comment by yyyyiiiinnnn** [comment]
Thank you! I have done "make install" and got the "setting.py" file, but when I run the second step, I get an error "no module named superpoint".

**Comment by yyyyiiiinnnn** [comment]
Thank you! I have done "make install" and got the "setting.py" file，but I encountered an error related to CUDA during runtime. Do I need to install CUDA? If so, which version should I install?

**Comment by rpautrat** [comment]
Hi, yes you need a GPU and CUDA installed to be able to run this code. I recommend following this post to know a combination of versions that works: https://github.com/rpautrat/SuperPoint/issues/173

**Comment by yyyyiiiinnnn** [comment]
thanks a lot！

**Comment by ouyangtiezhu74** [comment]
how did u find the settings.py?
I also install all the libraries in requirements.txt,but I didnt see one.

**Comment by ouyangtiezhu74** [comment]
Problem solved,thinks
