### ISSUE TITLE
MagicPoint Detector Evaluation experiments.

### ISSUE THREAD

**Issue by AliYoussef97** [rpautrat/SuperPoint#298]
Hello,

I am quite confused regarding the MagicPoint detector evaluation.

From my understanding: 

1- mp_synth-v6_no-aug_synth is when no photometric or homographic augmentation is applied.
2- mp_synth-v6_no-aug_synth-noise is when homographic augmentation is applied but not photometric.
3- mp_synth-v6_photo-aug_synth  is when homographic photometricis applied but not homographic .
4- 'mp_synth-v6_photo-aug_synth-noise' is when both are applied.

Is that correct? Or does noise mean that the gaussian noise images are included during evaluation?

Thank you.

**Comment by AliYoussef97** [comment]
@rpautrat Thank you so much.

Apolgies, I had one last question if you don't mind, when exporting the detections for MagicPoint evaluation, should the probabilties be multipled by the coressponding mask, as I am getting numerous detections at the bordering artifacts.

**Comment by rpautrat** [comment]
The multiplication is made in the training code, so it should be already masked during training. But if you want to be sure, you can also mask them during the export already.

**Comment by AliYoussef97** [comment]
Thank you!

**Comment by AliYoussef97** [comment]
@rpautrat Sorry remi, going back to the same question, in the notebook detector_evaluation_magic_point notebook, the prediction plot at the visualization cell appears to have no homography, as there are not black bordering artifacts? However, as you stated the expierments are either with noise or with Photometric augmentation, and homography is always enabled. So I am still slightly confused. 

I am asking, as I am getting around 97 97.5 mAP with and without noise and with an without photometric augmentation but homography is disabled. But whenever I enable homography, the black bordering artifacts are completely filled with predictions, I am not sure if that is normal behaviour or not.

Apologies for the persistent questions.
