### ISSUE TITLE
Restoring parameters problem

### ISSUE THREAD

**Issue by ivipsourcecode** [rpautrat/SuperPoint#30]
Ｉ have two problems:
(1) When i execute the program of the 4) step in the readme, as the following picture, when restoring about half parameters, it automatically stopped. is that normal?
(2) Another problem is that:
Is it means that what i need to do is to execute program instructed by step 1) 2) 3) 4) and 5) in the file of readme and i can get the right outcome? Because i do not know how to use other files in the file of configs like superpoint_coco.yaml and superpoint_hpatches.yaml. Those config files do not mentioned in the readme. I am a beginner and I am a little confused about those files. 
export_descriptors.py and export_detections are also not mentioned in the readme. 
I really need your help.

![221844453](https://user-images.githubusercontent.com/45613704/50625137-f0a2f800-0f60-11e9-8b5b-4aedf3ab9829.jpg)

**Comment by ivipsourcecode** [comment]
Thanks for your quick reply!  Does it mean that i should restart to execute the code from the first strep 1) in the file of README of  SuperPoint-superpoint_v1 when i use the branch SuperPoint-superpoint_v1 ?

**Comment by ivipsourcecode** [comment]
Thanks for your quick reply! Does it mean that i should restart to execute the code from the first strep 1) in the file of README of SuperPoint-superpoint_v1 when i use the branch SuperPoint-superpoint_v1 
? when i use the master, each step of 1) 2) 3) 4) takes about 13hours, so i ask you if i need to restart from the first step when i use the branch.

**Comment by ivipsourcecode** [comment]
When i use the master the 4) step in the README inclouding "To proceed to the evaluation, head over to no"
(1)![1181591968](https://user-images.githubusercontent.com/45613704/50635769-78532b80-0f8e-11e9-8327-f8e01420b8e4.jpg)
(2)

**Comment by ivipsourcecode** [comment]
I am sorry for misoperation and closed the comment. Another problem, when i run the step 4) using the master, as the picture(1) described that "To proceed to the evaluation, head over to notebooks/detector_repeatability_coco.ipynb. " I run the code in the picture(2), but i got the problem of  FileNotFoundError: [Errno 2] No such file or directory: '/home/ivip/lidongjiang/tmp2/outputs/mp_synth-v7_ha1-100_trained_no-topk_hp-v-repeat/0.npz', as described in the picture(3).
I think  the reason is that i do not generate the folder of mp_synth-v6_photo-hom-aug_ha2-100-3-old_coco-repeat, when i execute the program following the instruction 1) 2) 3) 4) in the file of README using the master. So how should i use the notebooks/detector_repeatability_coco.ipynb. I am so sorry that i have so many questions. Adding the last question, do i need to restart to execute the program from the step 1) if i use the branch? Looking forward to your reply.
(1)
![1181591968](https://user-images.githubusercontent.com/45613704/50638066-54481800-0f97-11e9-8fc9-7703ebe6be87.jpg)
(2)
![1942374343](https://user-images.githubusercontent.com/45613704/50638070-5a3df900-0f97-11e9-959b-2fc20b822b80.jpg)
(3)
![1379841731](https://user-images.githubusercontent.com/45613704/50638080-6033da00-0f97-11e9-8a45-8ae476bd1c24.jpg)

**Comment by lidongjiangBJTU** [comment]
@rpautrat

**Comment by ivipsourcecode** [comment]
@rpautrat

**Comment by rpautrat** [comment]
If you are in a hurry, you can just reuse the labels that you had generated in the step 2 of the branch master and train Superpoint with these labels (step 6 of the branch superpoint_v1). Those labels would be more accurate if you have actually repeated the steps 2 and 3 multiple times (say 1-2 times).

As for the error that you get when computing the repeatability, it probably comes from the name that you chose for the export. The argument --export_name that you used in step 4 should match the name of the experiment that you give in the notebook `notebooks/detector_repeatability_coco.ipynb` (currently mp_synth-v7_ha1-100_trained_no-topk_hp-v-repeat). So just change this mp_synth-v7_ha1-100_trained_no-topk_hp-v-repeat with the export_name that you used in step 4.

**Comment by lidongjiangBJTU** [comment]
Thank you. I will try.

**Comment by ivipsourcecode** [comment]
@rpautrat 
It is so weird, I have run "sudo python3 python.sh install", can you tell me something about this?
![image](https://user-images.githubusercontent.com/45613704/50699199-1e339280-1082-11e9-9493-6525b52123c6.png)

**Comment by lidongjiangBJTU** [comment]
@rpautrat

**Comment by ivipsourcecode** [comment]
@rpautrat

**Comment by rpautrat** [comment]
You don't have to call `python.sh` yourself, running `make install` in the root folder as mentioned in the ReadMe should be enough to install the package.
Do you get the same error after running `make install`?

**Comment by ivipsourcecode** [comment]
@rpautrat 
I have not solved this problem. You can see that I have run 'python3 setup.py install --user' like picture(1). But i always get the problem like picture(2), do you have any idea? hope your reply.
picture(1)
![image](https://user-images.githubusercontent.com/45613704/50807006-f3706500-1333-11e9-889e-31eba24b1a04.png)
picture(2)
![image](https://user-images.githubusercontent.com/45613704/50807016-fbc8a000-1333-11e9-9b0e-4cff3d2f5e51.png)

**Comment by rpautrat** [comment]
Again, you don't have to call `setup.py` yourself, running `make install` should install everything automatically. Have you tried it?
The line `pip install -e .` in the makefile should be the one actually installing the module.

**Comment by ivipsourcecode** [comment]
@rpautrat 
I think the problem is that "Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/li/SuperPoint/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/li/SuperPoint/" like picture(2), have you met this before? how should i do, and i don't find the method to deal with this problem.
picture(1)
![image](https://user-images.githubusercontent.com/45613704/50823467-07858800-136f-11e9-9bb3-202b7440f0dd.png)
picture(2)
![image](https://user-images.githubusercontent.com/45613704/50823506-1d934880-136f-11e9-871a-5a64c58b1a9d.png)

**Comment by ivipsourcecode** [comment]
And when i run 'sudo make install', I got this
![image](https://user-images.githubusercontent.com/45613704/50823874-fdb05480-136f-11e9-81be-fd82d19c1a90.png)

**Comment by rpautrat** [comment]
Can you try to use a Python environment instead of using the global Python of your computer? You can find how to set up a Python environment here: https://docs.python.org/3/tutorial/venv.html.
Once your environment is activated, you should be able to run `make install` (without sudo) and it will hopefully work.
