### ISSUE TITLE
magicpoint training in pytorch

### ISSUE THREAD

**Issue by BayRanger** [rpautrat/SuperPoint#306]
Hi, thanks for your work to reproduce sp
 In pytorch.
But. Noticing that the training of superpoint is based on the train/finetuning of magic point, it still needs the support of tf1 to train magic point.
My question would be that: is there any suggestion to reproduce the training of magicpoint in pyorch? Or if i understood correctly, the training of superpoint in a specific dataset based on the training of magicpoint in advance?

Best regards

**Comment by rpautrat** [comment]
Hi,

This repo is about retraining SuperPoint in Tensorflow, and we just offer the final model trained as pytorch weights as well (converted from the TF ones). But there is no way to do any retraining in pytorch
