### ISSUE TITLE
Export Model to ONNX

### ISSUE THREAD

**Issue by flashcolab** [rpautrat/SuperPoint#314]
Code to export PyTorch Model to ONNX? Keep Running into ValueError: expected 4D input (got 3D input). Once another Batch Dimension is added, new Error: Attribute Strides has incorrect size, The exported ONNX Model failed ONNX shape inference.

**Comment by rpautrat** [comment]
Hi, this is out of the scope of this repository as we did not provide this. I guess you need to debug it by yourself.
