### ISSUE TITLE
Can it be trained based on Pytorch model

### ISSUE THREAD

**Issue by SOCOOL666** [rpautrat/SuperPoint#328]
Hello dear blogger, I see Update: We have converted the Tensorflow model into a Pytorch one. Does this mean that the training model can be trained on Pytorch?Because I always get an error when training based on Tensorflow, I wonder if I can train based on Pytorch? If possible, please help to answer, thank you.

**Comment by rpautrat** [comment]
Hi, no this is not possible. The Pytorch model has been obtained by converting the Tensorflow one into Pytorch, but the training can only be done in Tensorflow.

**Comment by SOCOOL666** [comment]
Thanks for your answer, I will try Tensorflow again for training.
