### ISSUE TITLE
. pth file inference HPatches

### ISSUE THREAD

**Issue by haoxintian** [rpautrat/SuperPoint#329]
Hello, I would like to ask you about how to use the official pre trained weight file to evaluate the repeatability of HPatches inference?

I have completed the training of Coco using superpoint, but I found that export_detection.py does not support the push of. pth weight files. How can I solve this problem?

**Comment by rpautrat** [comment]
Hi, the .pth model is a model that has been converted to Pytorch. But the evaluation on HPatches is done on the original Tensorflow model (the one you obtained after training on COCO). If you want to compare to the one we trained, you can download the Tensorflow model from the links in the ReadMe: https://github.com/rpautrat/SuperPoint?tab=readme-ov-file#fine-tuning-a-pretrained-model

**Comment by haoxintian** [comment]
I understand, thank you very much for your answer!
