### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by ivipsourcecode** [rpautrat/SuperPoint#33]
@rpautrat 
When i run "python3 experiment.py train configs/magic-point_coco_train.yaml magic-point_coco", I got the AssertionError like picture (2). And i found that there does not exist the folder of mp_synth-v10_ha2-100 under /home/ivip/lidongjiang/tmp2/outputs. Under the folder of /home/ivip/lidongjiang/tmp2/outputs/ is .npz files created by step2) like the picture(1). Does this mean that i need to repeat the step2) ? it does cost much time. Can you give me some advise?
picture(1)
![121212](https://user-images.githubusercontent.com/45613704/50968993-ea3fed80-1517-11e9-9c48-f315e4ea9978.png)
picture(2)
![131313](https://user-images.githubusercontent.com/45613704/50969005-ee6c0b00-1517-11e9-9349-a7373d063e60.png)

**Comment by rpautrat** [comment]
Step 2 should have created the folder `outputs/magic-point_coco-export1` in which you will also find all the .npz containing the labels.
What you need to do is to change the parameter data->labels in `config/magic-point-coco-train.yaml` and to put the name of the folder with your own labels (outputs/magic-point_coco-export1).
