### ISSUE TITLE
Cannot download HPatches dataset

### ISSUE THREAD

**Issue by GoroYeh-HRI** [rpautrat/SuperPoint#330]
Hi, as stated in title, I cannot download HPatches dataset through the link provided in your README.
I also tried using the link from official HPatches github and didn't work.
Does anyone know how to download HPatches dataset?
Thank you. I really want to try your amazing work.

**Comment by SOCOOL666** [comment]
https://aistudio.baidu.com/datasetdetail/107865    You can visit the link to download it

**Comment by rpautrat** [comment]
Hi, I updated the HPatches link with that one: https://www.kaggle.com/api/v1/datasets/download/javidtheimmortal/hpatches-sequence-release
