### ISSUE TITLE
TypeError: invalid file: PosixPath

### ISSUE THREAD

**Issue by ivipsourcecode** [rpautrat/SuperPoint#36]
@rpautrat 
When I run "python3 experiment.py train configs/magic-point_shapes.yaml magic-point_synth", i got the following error. the version of python is 3.5.2. is it the reason?  I can not change this python version, because many other people still need to use. How should do?
![image](https://user-images.githubusercontent.com/45613704/51171173-26de6100-18eb-11e9-94d0-0991df4b627f.png)

**Comment by rpautrat** [comment]
Have you read my last message in https://github.com/rpautrat/SuperPoint/issues/34#issuecomment-453182060? The same remark applies here, this question has already been asked in the issues.

**Comment by ivipsourcecode** [comment]
I am so sorry and I have remembered Google is my best friend. Thank you

**Comment by xlong0513** [comment]
@ivipsourcecode 
Hi, i met the same questions with Python 3.5.2. How did u fix the problem? Thank u

**Comment by waleedrazakhan92** [comment]
> @ivipsourcecode
> Hi, i met the same questions with Python 3.5.2. How did u fix the problem? Thank u

https://stackoverflow.com/questions/42694112/when-using-pathlib-getting-error-typeerror-invalid-file-posixpathexample-t
