### ISSUE TITLE
Export detections time

### ISSUE THREAD

**Issue by mmmfarrell** [rpautrat/SuperPoint#45]
Hey @rpautrat, thanks again for the great implementation. I am currently in my second iteration of the training magic-point on the COCO dataset. It is taking forever though because the `export_detections` is running at 1.39 iterations per second. At this rate, it takes ~16 hrs to export all of the detections for the COCO train2014 dataset. Is this similar to what you were seeing? Or is there something wrong with my configuration? Thanks for your help!

![image](https://user-images.githubusercontent.com/21247551/54169062-e3115f00-4436-11e9-99c2-14bc8861b626.png)

**Comment by rpautrat** [comment]
Yes, exporting the detections unfortunately takes a long time, even though I tried to optimize it as much as possible. You can always reduce the number of homographies used per image (parameter num in homography_adaptation, 100 by default) to speed it up, but you willl also get a smaller gain in repeatability if you do that.

**Comment by mmmfarrell** [comment]
Ok, cool. Just wanted to make sure I wasn't wasting a bunch of time for no reason.

Any chance that you still have your experiments directory with the checkpoints? You mentioned you wanted to upload a pretrained model but didn't have time. If you email me the checkpoint and stuff, I'm happy to put in the time to make a nice pretrained script to run the system similar to MagicLeaps's [`demo_superpoint.py`](https://github.com/MagicLeapResearch/SuperPointPretrainedNetwork/blob/master/demo_superpoint.py).

**Comment by rpautrat** [comment]
I do have the directory with the checkpoints (the one created when training). I just shared with you the zip of this directory with Google Drive.

If you manage to export the weights and graph correctly and get a nice demo example with this, that would be awesome! I probably did a stupid error somewhere when exporting the weights, but had no time to check where was the problem until now. Let me know if it works (and feel free to do a PR)!

**Comment by mmmfarrell** [comment]
Awesome, I'll get on it and hopefully it works to make a nice demo for everyone!

**Comment by LIANGXINKAI** [comment]
> Awesome, I'll get on it and hopefully it works to make a nice demo for everyone!

can u share me with the checkpoints which rpautrat has trained

**Comment by mmmfarrell** [comment]
@LIANGXINKAI I am almost done with the demo. I will push up the demo/weights and make a PR in the next couple of hours.

**Comment by LIANGXINKAI** [comment]
@mmmfarrell  I look Foward to your work

**Comment by lidongjiangBJTU** [comment]
@mmmfarrell 
I have not been able to contact rpautrat and I want to ask you some questions I have encountered.
When I was recovering the model, I encountered the following problem, I have confirmed that the configuration is no problem，such as allow_soft_placement=True and write_meta_graph=True in the function of def save(self, checkpoint_path). I trained the model several times and still can't solve the problem. Have you encountered this problem?Could you give me some advises. I am looking forward your reply. Thank you very much.
******
InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'superpoint/train_tower0/sparse_softmax_cross_entropy_loss/xentropy/assert_equal/Assert/Assert': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
******

**Comment by mmmfarrell** [comment]
@lidongjiangBJTU I'm not sure I completely understand your problem. It seems like it may have something to do with your issue #29 . When do you see this error? You are able to train (i.e. run step 1) but you can't export the detections (i.e. run step 2)?

**Comment by lidongjiangBJTU** [comment]
@mmmfarrell 
Ok, let me describe the problem carefully. First of all, I have successfully trained the SuperPoint and the results  is shown in picture 1 below. I can also  evaluate the descriptors with homography estimation on HPatches. What I want to do now is to convert the trained SuperPoint model(as shown in picture 1 below) to the caffe frame. So the first step I have to do is to restore the SuperPoint' tensorflow model. And i use the program as picture 2 below. But i got the problem that InvalidArgumentError (see above for traceback): Cannot assign a device for operation  like picture 3 below. The online solution is to set "allow_soft_placement=True and write_meta_graph=True in the function of def save(self, checkpoint_path)." I have try this several times, but i can not solve the problem. I wonder if rpautrat also encountered the same problem, but i can not contact him. Please, can you try to restore the model like this? This problem has bothered me for a few days. Thank you very much.
![picture1](https://user-images.githubusercontent.com/44012688/55043125-9b621880-506f-11e9-9df0-e17b8c33fb53.png)
![picture2](https://user-images.githubusercontent.com/44012688/55043126-9bfaaf00-506f-11e9-8fc3-7c32a3e81b89.png)
![picture3](https://user-images.githubusercontent.com/44012688/55043127-9bfaaf00-506f-11e9-8fc7-b346fb4bcbd6.png)
