### ISSUE TITLE
Killed during train of using superpoint_hpatches.yaml

### ISSUE THREAD

**Issue by chaiein** [rpautrat/SuperPoint#49]
After 25000 iteration the training is killed. How to complete the iterations so that it saves some file in checkpoint. 

python experiment.py train configs/superpoint_coco.yaml superpoint_coco

**Comment by rpautrat** [comment]
Hi,
Try to change the param cache_in_memory to false in the config file, that should prevent the training from getting killed.

**Comment by chaiein** [comment]
Yup it solved the problem thank u :)
