### ISSUE TITLE
about run step2 and step3 several times

### ISSUE THREAD

**Issue by flamehaze1115** [rpautrat/SuperPoint#50]
![image](https://user-images.githubusercontent.com/17596726/54684976-a210fd00-4b50-11e9-9586-7fcda9f20d97.png)
Your work is quite great! The code is more like an artwork!
Well, I am wondering about whether the network's parameters will be restored in step3. It seems that when I run the step3, the network will be initialized and trained again. There seems no network restoring?
I haven't digged deeply in the codes, maybe I have a misunderstanding.

**Comment by mmmfarrell** [comment]
It is true that learned weights are not restored in step 3. Remi has previously mentioned that this is something he might like to add in the future, but is not currently implemented (see [this issue](https://github.com/rpautrat/SuperPoint/issues/37#issuecomment-454716661)). The weights are simply used to generate the "ground truth" feature point locations that are used for training. Though the MagicLeap SuperPoint paper mentions that they reuse the weights. Remi was has shown that his method also produces good results.

**Comment by flamehaze1115** [comment]
@mmmfarrell Thank you very much for such detailed explanation. The code provides a function net.load(), I have used this function easily to restore the weights.
