### ISSUE TITLE
Is it useful for document page corner detection?

### ISSUE THREAD

**Issue by ldenoue** [rpautrat/SuperPoint#51]
Not an issue, but question: I wonder if I could train this on a synthetic dataset that container only corners like the ones from images of documents to be scanned with a camera.
Presumably it could learn their positions, right?

**Comment by rpautrat** [comment]
Absolutly, SuperPoint can be trained on this kind of dataset, provided that you have such a synthetic dataset. The current synthetic dataset already contains a lot of corners, so the dataset for your application shouldn't be too hard to create.

**Comment by ldenoue** [comment]
I thought I’d just remove all synthetic shapes except corners, and train on this subset the synthetic data.
Then apply the result directly on my images to see what I get.

**Comment by rpautrat** [comment]
Yes, I think you can start this way. You will probably detect other kind of corners as well however. You might need to refine the detections afterwards.
