### ISSUE TITLE
Experiments parameters missing like harris_coco-repeat

### ISSUE THREAD

**Issue by chaiein** [rpautrat/SuperPoint#52]
In the descriptors_evaluation_on_hpatches.ipynb

 experiments = [
    'mp_synth-v6_photo-hom-aug_ha2-100-3-old_coco-repeat', 'harris_coco-repeat']
confidence_thresholds = [0.015, 0]

file not found. How to generate the harris_coco_repeat?

**Comment by rpautrat** [comment]
I guess you meant detector_repeatability_coco.ipynb.

harris_coco-repeat is generated by choosing 'harris' in method->model of the config file `configs/classical-detectors_repeatability.yaml` and then running
`python export_detections_repeatability.py configs/classical-detectors_repeatability.yaml magic-point_coco --export_name harris_coco-repeat`
