### ISSUE TITLE
detector_evaluation_magic_point  error

### ISSUE THREAD

**Issue by LZHDOPE** [rpautrat/SuperPoint#53]
run PR curve:  
    KeyError: 'prob is not a file in the archive'
run Localization Error:
    KeyError: 'keypoint_map is not a file in the archive'
run Visualization: 
    KeyError:'image is not a file in the archive'

where is the problem?

**Comment by LZHDOPE** [comment]
another question : when i run step 4, Evaluating the repeatability on HPatches, error occurs:

/home/liu/SuperPoint/superpoint/HPatches/hpatches-sequences-release/H_1_2 not found

i have checked the file, Hpathes datasets only have H_ref_1,  H_ref_2...

**Comment by chaiein** [comment]
replace the name H_1 with H_ref in the code.

**Comment by LZHDOPE** [comment]
Thanks, @chaiein   
i change the code but
 **ValueError: could not convert string to float: '0.49202,0.0057754,242.06'**

then i add delimiter="," but
homographies.append(np.loadtxt(str(Path(path, "H_ref_" + str(i))), delimiter=','))
**tensorflow.python.framework.errors_impl.InvalidArgumentError: pyfunc_4 returns 0 values, but expects to see 1 values.**

**Comment by chaiein** [comment]
Replace the line with string type
that is
homographies.append(np.loadtxt(str(Path(path, "H_ref_" + str(i))),dtype='str'))

**Comment by LZHDOPE** [comment]
thanks, @chaiein
i find another version of Hpathes datasets.  i change the datasets and now it works well.

Another question, how to run the notebooks of **detector_evaluation_magic_point.ipynb**?
the result of which steps should be put in the experiments? How to generate experiments like  'mp_synth-v6_no-aug_synth' ?

the original code is:
**experiments = [
    'mp_synth-v6_no-aug_synth', 'mp_synth-v6_no-aug_synth-noise',
    'mp_synth-v6_photo-aug_synth', 'mp_synth-v6_photo-aug_synth-noise',
    'harris_synth-v6', 'harris_synth-v6-noise',
    'shi_synth-v6', 'shi_synth-v6-noise',
    'fast_synth-v6', 'fast_synth-v6-noise',
]
confidence_thresholds = [0.1]*4 + [90000]*2 + [0.06]*2 + [40]*2**

Thanks again!

**Comment by chaiein** [comment]
@LZHDOPE I am also not sure how to use the experiments. So I have created a issue in this link.
https://github.com/rpautrat/SuperPoint/issues/52

**Comment by LZHDOPE** [comment]
Hi, @chaiein   check out this:
https://github.com/rpautrat/SuperPoint/issues/12#issuecomment-417237829

**Comment by chaiein** [comment]
@LZHDOPE  Thank you. But there is a error of is_training not found. I addressed it as new issue https://github.com/rpautrat/SuperPoint/issues/54

**Comment by chaiein** [comment]
> thanks, @chaiein
> i find another version of Hpathes datasets. i change the datasets and now it works well.
> 
> Another question, how to run the notebooks of **detector_evaluation_magic_point.ipynb**?
> the result of which steps should be put in the experiments? How to generate experiments like 'mp_synth-v6_no-aug_synth' ?
> 
> the original code is:
> experiments = [
> 'mp_synth-v6_no-aug_synth', 'mp_synth-v6_no-aug_synth-noise',
> 'mp_synth-v6_photo-aug_synth', 'mp_synth-v6_photo-aug_synth-noise',
> 'harris_synth-v6', 'harris_synth-v6-noise',
> 'shi_synth-v6', 'shi_synth-v6-noise',
> 'fast_synth-v6', 'fast_synth-v6-noise',
> ]
> confidence_thresholds = [0.1]*4 + [90000]*2 + [0.06]*2 + [40]*2
> 
> Thanks again!

Which is the other HP dataset available?

**Comment by LZHDOPE** [comment]
@chaiein 
https://github.com/hpatches/hpatches-dataset
download the 1.3GB version:   HPatches full sequences [1.3GB].

**Comment by chaiein** [comment]
> @chaiein
> https://github.com/hpatches/hpatches-dataset
> download the 1.3GB version: HPatches full sequences [1.3GB].

Thank you.

**Comment by rpautrat** [comment]
Hi @LZHDOPE and @chaiein, sorry for the late answer.

They probably released a new version of HPatches in the meantime, which would explain your error messages. Thank you for linking the right dataset.

If you want to get the following experiments:
`experiments = [
'mp_synth-v6_no-aug_synth', 'mp_synth-v6_no-aug_synth-noise',
'mp_synth-v6_photo-aug_synth', 'mp_synth-v6_photo-aug_synth-noise',
'harris_synth-v6', 'harris_synth-v6-noise',
'shi_synth-v6', 'shi_synth-v6-noise',
'fast_synth-v6', 'fast_synth-v6-noise',
]`
, you should use the following config files: `configs/magic-point_shapes.yaml` (for the mp_synth-v6 experiments) and `configs/classical-detectors_shapes.yaml` (for the harris, shi and fast experiments).

The full script would for example be:
`python export_detections.py configs/magic-point_shapes.yaml magic-point_synth`

**Comment by l1346792580123** [comment]
@LZHDOPE 
have you solved your first problem about the KeyError: 'prob is not a file in the archive'? I run another notebook and meet the same problem.

**Comment by brade31919** [comment]
@l1346792580123 
Removing the --pred_only flag in exporting detections can fix the problem.

**Comment by water-wave** [comment]
> @chaiein
> https://github.com/hpatches/hpatches-dataset
> download the 1.3GB version: HPatches full sequences [1.3GB].

sorry to bother,can you send me this dataset, the website i can't open.

**Comment by rpautrat** [comment]
Hi, I think the HPatches website was down a few days ago when you tried to download the dataset. But now it seems to be working again (at least it is the case for me).
