### ISSUE TITLE
Is there has Pytorch version code?

### ISSUE THREAD

**Issue by siyuada** [rpautrat/SuperPoint#56]
Really thanks for your work, but in the paper said, ''All training is done using PyTorch''. And this opensource code is using Tensorflow. I wonder that if there has a Pytorch version code for SuperPoint?

**Comment by rpautrat** [comment]
Hi,
Yes, Magic Leap released a Pytorch version with pretrained weights in https://github.com/MagicLeapResearch/SuperPointPretrainedNetwork

**Comment by siyuada** [comment]
Thanks.
