### ISSUE TITLE
Using which descriptor the corner points are detected intially on the synthetic shapes.

### ISSUE THREAD

**Issue by chaiein** [rpautrat/SuperPoint#57]
In magic-point_shapes.yaml
if data.name is the name of the file. What does the primitive:all mean. How are the corner points detected on the synthetic shapes?

**Comment by rpautrat** [comment]
"All primitives" means that you will use all the geometrical shapes of the synthetic dataset (lines, polygons, ellipses, stars, checkerboards, stripes, 3D cubes and gaussian noise).

When creating the synthetic dataset, we have access to the corners of those shapes (because we created them), so we can store the labels for the point detections at that point.

**Comment by chaiein** [comment]
how to access the corner points on the geometric shapes? Isnt it using any traditional corner detector algorithms?

**Comment by rpautrat** [comment]
No, again we have the corner points directly when creating the geometric shapes. For example if you create a square then you know where the four corners are, because you are the one that drew the square.

**Comment by chaiein** [comment]
Thank u. I couldn't find where these points are given as input during training in any file.

**Comment by rpautrat** [comment]
When creating the synthetic dataset in `datasets/synthetic_shapes.py`, the corner points are stored in the key 'keypoints' and this is reused later during training.

What do you mean by "changing to other detectors" exactly? You want to train a detector on the geometric shapes different from MagicPoint?

**Comment by chaiein** [comment]
I mean changing to the blob or edges form instead or corner points.

**Comment by rpautrat** [comment]
In that case you need to modify the files `datasets/synthetic_shapes.py` and `datasets/synthetic_dataset.py` by adding your own shapes if you want new ones, and for each function in `datasets/synthetic_dataset.py`, you shouldn't return the corner points, but the lines, blob, etc.

**Comment by chaiein** [comment]
Okay, I got it. Thank you so much.
