### ISSUE TITLE
errors when Evaluating the repeatability on HPatches

### ISSUE THREAD

**Issue by zhangxuying1995** [rpautrat/SuperPoint#58]
hello, when evaluating the repeataability on HPatches, with the command 'python export_detections_repeatability.py configs/magic-point_repeatability.yaml magic-point_coco --export_name=magic-point_hpatches-repeatability-v' , i met some errors. 
firstly, as follow picture:
![1](https://user-images.githubusercontent.com/47649909/55864042-45808b00-5bae-11e9-911e-92a8d24a8b84.PNG)
it shows, the /datasets/patches_dataset.py, change the 40th row code, error, HPatches/v_fest doesn't have the files whose name start with 'H_1_2'. i see that dir, and i find the dir surely doesn't contain files whose name start with 'H_1_', but contains files whose name start with 'H_ref_', as follow picture:
![2](https://user-images.githubusercontent.com/47649909/55864655-7a411200-5baf-11e9-9b03-5e82ec9d70d7.PNG)
so, i modified the /datasets/patches_dataset.py, change the 40th row code, from 'H_1_' to 'H_ref_', and run the command again, however i met a new error, as follow picture, 
![3](https://user-images.githubusercontent.com/47649909/55864940-05220c80-5bb0-11e9-8968-ddd65456cb4b.PNG)
it shows, ValueError:could not convert string to float, and the 40th row error again, however, i see the code file, i don't find the convert from string to float, why this error appear, what should i do so that i could run this command successfully? thanks you

**Comment by rpautrat** [comment]
Hi,

These issues have been tackled in https://github.com/rpautrat/SuperPoint/issues/53.

Please use the following HPatches dataset to avoid these problems: http://icvl.ee.ic.ac.uk/vbalnt/hpatches/hpatches-sequences-release.tar.gz

**Comment by zhangxuying1995** [comment]
Hi, rpautrat, this problem is tackled, thanks a lot, .
i still have some questions to ask you.
first, i run the command, but when the process arrive 58%, the code automatically end, as the follow picture:
![image](https://user-images.githubusercontent.com/47649909/55879810-0b28e500-5bd2-11e9-9a66-d97963f3a37a.png)
is there something wrong?
second, i see your answer on  #53. 
i want to know, if i want to get the p-r curve, mAP and Localization Error about the experiments = [
    'mp_synth-v6_no-aug_synth', 'mp_synth-v6_no-aug_synth-noise',
    'mp_synth-v6_photo-aug_synth', 'mp_synth-v6_photo-aug_synth-noise',
    'harris_synth-v6', 'harris_synth-v6-noise',
    'shi_synth-v6', 'shi_synth-v6-noise',
    'fast_synth-v6', 'fast_synth-v6-noise']
i first run the command 'python export_detections.py configs/magic-point_shapes.yaml magic-point_synth' as you say to generate experiment data of magicpoint.
but, when refer to classical detectors, what command is? 
i know the config file of classical detectors is configs/classical-detectors_shapes.yaml, however what the next parameter that points to model of this command is？
third，i want to know the command to generate repeatability of classical detectors, the difficulty i met is similar to the above question.
Thank you.

**Comment by rpautrat** [comment]
1) This has already been answered several times in the issues, for example here: https://github.com/rpautrat/SuperPoint/issues/24#issuecomment-447245197

2) Use `python export_detections.py configs/classical-detectors_shapes.yaml magic-point_synth`. The name of the model 'magic-point_synth' at the end won't be used at all with this config file (so you could actually use any name of model with the same result).

3) Use for example `python export_detections_repeatability.py configs/classical-detectors_repeatability.yaml magic-point --export_name=fast_hpatches-repeatability-v`
The name of the classical detector has to be modified in `configs/classical-detectors_repeatability.yaml` and the name of the model (here 'magic-point') won't be used here, so you can put anything and it should still work.

**Comment by zhangxuying1995** [comment]
ok, i understand , thank you
