### ISSUE TITLE
TypeError: Sample_homography() got unexpected argument 'perspective_amplitude'

### ISSUE THREAD

**Issue by chaiein** [rpautrat/SuperPoint#60]
On the 5th Step while generating. 

Python generate_coco_patches.py configs/coco_patches_generation.yaml
I got the perspective amplitude problem. How to solve this error?

**Comment by rpautrat** [comment]
Indeed, this script has not been used for a while and the perspective_amplitude parameter changed in the meantime. I corrected the bug, so it should work now.

**Comment by chaiein** [comment]
Yes it works. Thank u.
