### ISSUE TITLE
Notebook superpoint no module found

### ISSUE THREAD

**Issue by chaiein** [rpautrat/SuperPoint#64]
In detector_repeatability_coco.ipynb file 
 from superpoint.settings import EXPER_PATH

on execution using notebook 
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-ff0633b5da75> in <module>()
      3 import matplotlib.pyplot as plt
      4 from pathlib import Path
----> 5 from superpoint.settings import EXPER_PATH
      6 import superpoint.evaluations.detector_evaluation as ev
      7 from utils import plot_imgs

ModuleNotFoundError: No module named 'superpoint'
I tried to remove the word superpoint but it didnt work.

**Comment by rpautrat** [comment]
Did you install the package superpoint with the command `make install`?

**Comment by chaiein** [comment]
yes I installed.

**Comment by rpautrat** [comment]
Can you import superpoint in a python terminal anywhere on your computer (outside of the folder SuperPoint)? If not, this is a problem related to your installation of the package superpoint. Please check that you are using the right python environment (if you use an environment) and that superpoint is accessible in your PYTHONPATH. Make also sure that you are consistent between the way you installed superpoint and the python version you are using (pip with python2 and pip3 with python3).

**Comment by chaiein** [comment]
I moved the .ipynb file outside the notebook to SuperPoint main folder. Now it works. Thank you.

**Comment by rpautrat** [comment]
Yes but still, it means that your package superpoint is not correctly installed and that you can only run it from the SuperPoint folder...

**Comment by chaiein** [comment]
> Yes but still, it means that your package superpoint is not correctly installed and that you can only run it from the SuperPoint folder...

followed all the 7steps. They were successful. How to solve this issue without moving the file?

**Comment by rpautrat** [comment]
Are you using a python environment?

**Comment by chaiein** [comment]
> Are you using a python environment?

Yes python 3.6.8

**Comment by rpautrat** [comment]
I mean with virtualenv, venv, anaconda, etc. If yes, then can you move to the folder `SuperPoint` and run `pip install -e .`?
 If you are only using Python3 without environment, this should rather be `pip3 install -e .`

**Comment by chaiein** [comment]
Yes superpoint package is successfully installed. Thank u.
Installing collected packages: superpoint
  Found existing installation: superpoint 0.0
    Can't uninstall 'superpoint'. No files were found to uninstall.
  Running setup.py develop for superpoint
Successfully installed superpoint

**Comment by rpautrat** [comment]
Ok, great!
