### ISSUE TITLE
Unsupported operand type(s) for /: nonetype and float

### ISSUE THREAD

**Issue by chaiein** [rpautrat/SuperPoint#66]
In visualize_synthetic-shapes.ipynb

`for i in range(8):
    plot_imgs([display(next(data))/255. for _ in range(4)], dpi=200)`
results in unsupported operand type(s) for /: 'NoneType' and 'float'

How to solve this issue?

**Comment by rpautrat** [comment]
It means that `display` returned `None`, so first check that the output of `next(data)` is not `None` for you and otherwise search why `draw_keypoints` could return `None`. For me this notebook works, so it should be something related to your configuration.
