### ISSUE TITLE
In visualize_coco_augmentation perspective_amplitude issue

### ISSUE THREAD

**Issue by chaiein** [rpautrat/SuperPoint#68]
Using notebooks for visualization at 

dataset = Coco(**config)
results in 
TypeError: sample_homography() got an unexpected keyword argument 'perspective_amplitude'.

But I dont know how to modify it. Why does this perspective amplitude problem exist in notebook though its solved during coco patch generation.

**Comment by chaiein** [comment]
I solved this issue just by printing some lines in sample homographies and saved it. I am not sure where did it grab the old data before.

**Comment by rpautrat** [comment]
The problem was again due to the fact that it was an old notebook that had not been updated with the newer version of sample_homography(). The problem should be fixed now.
