### ISSUE TITLE
Syntax error in Coco_patches_generation.yaml

### ISSUE THREAD

**Issue by chaiein** [rpautrat/SuperPoint#70]
python configs/coco_patches_generation.yaml generate_coco_patches.py 

Shows syntaxError at homographies: 
  File "configs/coco_patches_generation.yaml", line 1
    homographies:
                       ^

SyntaxError: invalid syntax

**Comment by rpautrat** [comment]
Have you just thought one second before posting this? Look at the command you ran...

The issues are here to help you when you struggle on a problem related to the repo, not for debugging issues. Please try to debug by yourself before posting anything here.

**Comment by chaiein** [comment]
Sorry for the post. thank u. I got my mistake.
