### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by brade31919** [rpautrat/SuperPoint#73]
Hi @rpautrat ,

First, thank you for sharing this great work with us!!
In the data preprocessing pipeline, I found that images are only read and decode to uint8 without being scaling to 0 to 1 with type tf.float32.
Though I think it's not a big deal, just let you know because image would be scale to 0 to 1 in most of the works.

Thank you!

**Comment by rpautrat** [comment]
Indeed, it shouldn't be a big deal, but thanks for pointing it out. If I have enough time in the future, I will try normalize the images to compare the performance and make it more "standard".
