### ISSUE TITLE
Cannot reproduce descriptor evaluation results

### ISSUE THREAD

**Issue by supercoolgreatcoder** [rpautrat/SuperPoint#74]
I am unable to reproduce descriptor evaluation results on HPatches. 
Steps I followed:
1. Train magic point on synth dataset: https://gist.github.com/supercoolgreatcoder/177a2f70af86f86347fc8994e5b761b5
2. Export labels for coco dataset using trained model
3. Train magic point model on coco dataset using labels from step 2
https://gist.github.com/supercoolgreatcoder/b829d72d2a3ed3fc2a2810b48d168e0d
4. Export labels for coco dataset using trained model
5. Train superpoint model on coco dataset using labels from step 4:
https://gist.github.com/supercoolgreatcoder/41b4bf9bab6e8692fd698333adc7f960
6. Export descriptors for HPatches and run descriptor evaluation. Got:
  superpoint_hpatches-v: 0.19322033898305085
  superpoint_hpatches-i: 0.8947368421052632
7. Train superpoint model on coco dataset using labels from step 2:
https://gist.github.com/supercoolgreatcoder/cbe570a2faf835297b04764aa082a777
8. Export descriptors for HPatches and run descriptor evaluation. Got:
  superpoint_hpatches-v: 0.2135593220338983
  superpoint_hpatches-i: 0.9368421052631579

Results from step 8 seem to be closer to those reported in the repo README if compared to results from step 6. @rpautrat , Could you please take a look at loss/precision/recall in training logs and suggest what might cause divergence from reported numbers. 
p.s. I used default config parameters in all runs.

**Comment by rpautrat** [comment]
Hi !

I see two major differences with my own training.

First, I didn't trained MagicPoint on the synthetic dataset for so long because I noticed a kind of overfitting after some time. I used 40 000 iterations in practice.

Secondly, after step 4, I retrained MagicPoint on COCO and reexported the labels with homographic adaptation a second time (it increased a bit their repeatability). Those new labels where the one I used to train SuperPoint.

I hope that with these two modifications you will get better results.

**Comment by supercoolgreatcoder** [comment]
@rpautrat , thanks for the hints. I tried to retrain superpoint from scratch following your suggestions:
1. Train magic point on synth dataset for 40k iterations only: 
https://gist.github.com/supercoolgreatcoder/6aa87520ac539c982d9c1edb507b62f5
2. Export labels for coco dataset using trained model
3. Train magic point model on coco dataset using labels from step 2
https://gist.github.com/supercoolgreatcoder/e0ec5b666c51ae36fb4043bea50424b7
4. Export labels for coco dataset using trained model
5. Train magic point model on coco dataset using labels from step 4
https://gist.github.com/supercoolgreatcoder/7cff54ab1f15e17275e36a547e558b39
6. Export labels for coco dataset using trained model
7. Train superpoint model on coco dataset using labels from step 6:
https://gist.github.com/supercoolgreatcoder/f7e2b3fd371458a91eab5e060dc96c91
8. Export descriptors for HPatches and run descriptor evaluation. Got:
superpoint_hpatches-v: 0.17288135593220338
superpoint_hpatches-i: 0.8807017543859649

One issue I noticed is that retraining magic point on coco (step 5) results in lower recall and higher loss if compared to step 3. 
As a consequence, superpoint recall, precision and loss are worse compared to step 7 from my previous post. 
Is there anything else you can think of I am missing?
Thank you

**Comment by githubfragments** [comment]
I had the same problem. Do you figure out the solution? @supercoolgreatcoder

**Comment by supercoolgreatcoder** [comment]
@githubfragments no, I gave up
If you succeed, let us know
