### ISSUE TITLE
Issue with 4th step

### ISSUE THREAD

**Issue by DaddyWesker** [rpautrat/SuperPoint#75]
Hello!
trying to reproduce your results step-by-step. Walked through 3 steps and now, 4th step "Evaluating the repeatability on HPatches".
Launching, process started and... stops on 58% with no errors (see pic). Firstly i'vegot some tqdm-related errors, then i've updated tqdm and now just no errors at all. Unfortunately i haven't saved tqdm errors...
Thanks in advance
![Screenshot from 2019-05-22 12-44-55](https://user-images.githubusercontent.com/10774222/58165046-a14f3100-7c8f-11e9-91f4-fe0dfa6f1178.png)

**Comment by rpautrat** [comment]
Hi, this issue has already been answered several times, including here: https://github.com/rpautrat/SuperPoint/issues/24#issuecomment-447245197

**Comment by DaddyWesker** [comment]
Oh... sorry for that. Haven't found it.
