### ISSUE TITLE
[1] killed

### ISSUE THREAD

**Issue by gentle-li** [rpautrat/SuperPoint#78]
Hi, I am running the first command and I get the following error，the data set has been generated, is the error that occurred in get_model
![image](https://user-images.githubusercontent.com/38391056/58546519-1beff180-8238-11e9-8a9e-8c470ec3acd0.png)
After the program died, I looked at the memory.
![image](https://user-images.githubusercontent.com/38391056/58546575-3aee8380-8238-11e9-8fe1-fd282f9d56bf.png)
i am using 4 GPUs
Is this what is the reason?

**Comment by rpautrat** [comment]
Hi, is the parameter 'cache_in_memory' set to True in your config file `configs/magic-point_shapes.yaml`? If yes, can you set it to False and see if it solves your problem?

**Comment by gentle-li** [comment]
I set up 1 GPU, the program runs normally, but it is slow, I will try your method for a while.thanks!
