### ISSUE TITLE
Hpatch Evaluation 

### ISSUE THREAD

**Issue by Merical** [rpautrat/SuperPoint#80]
Hi, I'm working on the evaluation of my implementation. I've tried the HPatches and the HPatches Sequences but the outcome of descriptor evaluation is weird:

orb result: 
Viewpoint correctness:  0.0
Illustration correctness:  0.5043859649122807
Sum correctness:  0.2478448275862069
Viewpoint mean_dist:  196.98830059689362
Illustration mean_dist:  135.68376026795727
Sum mean_dist:  166.8645178490542

sift result: 
Viewpoint correctness:  0.0
Illustration correctness:  0.8464912280701754
Sum correctness:  0.41594827586206895
Viewpoint mean_dist:  244.99917022423983
Illustration mean_dist:  109.58537540527794
Sum mean_dist:  178.45963311492238

My result: 
Viewpoint correctness:  0.0
Illustration correctness:  0.8640350877192983
Sum correctness:  0.4245689655172414

Viewpoint mean_dist:  177.45306199544686
Illustration mean_dist:  10.95750400704052
Sum mean_dist:  95.6405895356265

As you can see, the Viewpoint correctness is 0 and its mean_dist is extremely high. 
Here is my code:
```
    matches = bf.match(desc_ref, desc_warped)
    matches_idx = np.array([m.queryIdx for m in matches])
    m_keypoints = kps_ref_raw[matches_idx, :]
    matches_idx = np.array([m.trainIdx for m in matches])
    m_warped_keypoints = kps_warped_raw[matches_idx, :]
    homo, inliers = cv2.findHomography(m_keypoints[:, [0, 1]],
                                       m_warped_keypoints[:, [0, 1]],
                                       cv2.RANSAC)

    real_homo = np.loadtxt(os.path.join(path, 'H_1_' + str(i)))
    corners = np.array([[0, 0, 1],
                        [0, shape[1] - 1, 1],
                        [shape[0] - 1, 0, 1],
                        [shape[0] - 1, shape[1] - 1, 1]])
    real_warped_corners = np.dot(corners, np.transpose(real_homo))
    real_warped_corners = real_warped_corners[:, :2] / real_warped_corners[:, 2:]
    warped_corners = np.dot(corners, np.transpose(homo))
    warped_corners = warped_corners[:, :2] / warped_corners[:, 2:]
    mean_dist = np.mean(np.linalg.norm(real_warped_corners - warped_corners, axis=1))
    correctness = float(mean_dist <= correctness_thresh)
```

And an example with v_adam 1_2 is pictured:
the warped ref picture with predicted homo and real homo
![Figure_0](https://user-images.githubusercontent.com/26246729/59435767-e85cbc00-8e20-11e9-827f-97d8ea6e1462.png)
the matching result:
![Figure_1](https://user-images.githubusercontent.com/26246729/59435741-d9760980-8e20-11e9-8271-97489ebe522d.png)
and I warped 4 points, the blue points keypoints are waped by the real homo and read ones are warped by the predicted homo
![Figure_2](https://user-images.githubusercontent.com/26246729/59435754-e09d1780-8e20-11e9-9cbb-94d2ca4c4d1d.png)

Can you please help me with it?

**Comment by rpautrat** [comment]
This should have been solved in eccbd5e0bfcec343ad2ae90ac7eca25e551b434f. Closing this issue now.
