### ISSUE TITLE
Unexpected MagicPoint detection results on coco

### ISSUE THREAD

**Issue by Le0000000000n** [rpautrat/SuperPoint#82]
Hi!

When I train MagicPoint on coco, it tends to give a set of points around the true interest point. The second round MagicPoint training on coco are even worse than the first round. I retrain the model from the very beginning step 1 and the same thing reoccured. You can find a few examples below. May I ask have you ever run into similar problems like this? What could possibly have gone wrong? Any hints are welcome. Thanks!

![image](https://user-images.githubusercontent.com/7270964/60001214-9590c900-9698-11e9-9438-592e80c818d6.png)
![image](https://user-images.githubusercontent.com/7270964/60001265-b6591e80-9698-11e9-9416-bc1099c79d4d.png)
![image](https://user-images.githubusercontent.com/7270964/60001310-cb35b200-9698-11e9-8c0a-077975cb13ed.png)
![image](https://user-images.githubusercontent.com/7270964/60001351-e3a5cc80-9698-11e9-8fe1-1898c5d893ca.png)

**Comment by rpautrat** [comment]
This issue should have been solved in the most recent version of the network. The problem was a resize of the image during homography adaptation that involuntary spread the the activation of the heatmap on keypoints.
