### ISSUE TITLE
OOM when training SuperPoint with batch_size=1, GPU_RAM=22G

### ISSUE THREAD

**Issue by Le0000000000n** [rpautrat/SuperPoint#83]
Hi! I have read a few other issues about this and the conclusion was the resolution too big. My configurations are 1024x1224 resolution, 1 batch size, P40 GPU with 23G GPU_RAM, 128G CPU_RAM. Does it make sense to have OOM?

BTW, even though I saw "sess_config.gpu_options.allow_growth = True" in codes, it still take up all the GPU_RAM when training. For example when training magic point, it will take up 11.7 if given 12.4, and 21.9 if given 22.9. Have you ever run into such problems?

Thanks!

**Comment by rpautrat** [comment]
Hi!
Yes, I think that your current configuration reaches the OOM, but not by far. I personally used smaller images (roughly 3x2 times smaller), but with half your GPU RAM and a batch of 3.
So if you try with a resolution twice smaller (512x612), I think that it should work for you. Or even slightly better resolution should also work.

**Comment by Le0000000000n** [comment]
I ended up with 360x432 and batch of 1. Thanks!
