### ISSUE TITLE
About the 7th step, some problem in notebooks/descriptors_evaluation_on_hpatches.ipynb

### ISSUE THREAD

**Issue by zjk15068083791** [rpautrat/SuperPoint#86]
Dear Remi, Thank you so much for your kind work!
When I head over to notebooks/descriptors_evaluation_on_hpatches.ipynb, I met some problems which was shown in the following picture. 
I tried to solve it by myself, but I had no idea~ Could you give me some advice? I would be very appreciate if I could receive your reply~
Thank you again for your kindness! @rpautrat 

![descriptors_hpatches_visualization](https://user-images.githubusercontent.com/39995121/61131323-88bf0280-a4eb-11e9-99f1-2c8c81095844.png)

**Comment by rpautrat** [comment]
Hi @zjk15068083791!

You probably need to convert your images to int8, for example by adding those two lines before the return statement:
```
img1 = img1.astype(np.int8)
img2 = img2.astype(np.int8)
```

**Comment by zjk15068083791** [comment]
> Hi @zjk15068083791!
> 
> You probably need to convert your images to int8, for example by adding those two lines before the return statement:
> 
> ```
> img1 = img1.astype(np.int8)
> img2 = img2.astype(np.int8)
> ```

Thank you so much for your quick reply! I followed your advice, but I still received the following feedback~ 

![1562940744](https://user-images.githubusercontent.com/39995121/61134445-3208f700-a4f2-11e9-9a93-ffbcb04d9e24.png)
![descriptors_hpatches_visualization(1)](https://user-images.githubusercontent.com/39995121/61134617-94fa8e00-a4f2-11e9-9013-0ec8241aa183.png)

**Comment by rpautrat** [comment]
Sorry it's my fault: the data format expected by OpenCV is actually an unsigned integer. So you should rather use this:
```
img1 = img1.astype(np.uint8)
img2 = img2.astype(np.uint8)
```

**Comment by zjk15068083791** [comment]
> Sorry it's my fault: the data format expected by OpenCV is actually an unsigned integer. So you should rather use this:
> 
> ```
> img1 = img1.astype(np.uint8)
> img2 = img2.astype(np.uint8)
> ```

Thank you so much for your kindness! It works! So thanks~~

**Comment by rpautrat** [comment]
No problem :)
