### ISSUE TITLE
some questions about evaluation

### ISSUE THREAD

**Issue by shylockyuan** [rpautrat/SuperPoint#87]
Hello, I am confused about the algorithm.
Q1: evaluation about detectors: TP is the number of distances which is lower than distance_thresh between the detections and ground truth. But how to ensure the number of detections is equal to the number of ground truth. If not equal, how to sure the locations of detections are subtracted from their corresponding ground truth locations?
Q2: compute_pr : This function calculates the pr of 200 images when the prob goes from high to low. I don’t know why presion concatnate [0]and[0].Why not [1] and [0]. And I don’t understand the calculation of mAP.  Why not mAP = np.mean(presion[1:-1])?
Thanks in advance!

**Comment by rpautrat** [comment]
Hi,

Q1: We cannot ensure that we have exactly the same number of predictions as there are ground truths, but when several detections are close to the same ground truth point, only the detection with highest score is considered as true positive and all the others are considered as false negatives.

Q2: Can you copy the part of the code you are mentioning? Thanks.
The mAP is not the mean of the precision, check its definition online. One way to define it is the area under the precision/recall curve, which is what we do in the line `np.sum(precision[1:] * (recall[1:] - recall[:-1]))`. We just discretize the integral in a sum of areas of rectangles, each of size `precision[i] x (recall[i] - recall[i-1])`.

**Comment by shylockyuan** [comment]
Hello, I tried to use the model of SuperPoint but failed. 
1.	I try “python export_model.py configs/superpoint_coco.yaml model” to produce the model. 
2.	Create a new file which route is “superpoint/extract interest points”. And use tf.saved_model.loader.load(sess,[“predict”,”./EXPER_DIR/superpoint_coco”]) to import model.
Could you give me some hints?
Thank you very much.

**Comment by rpautrat** [comment]
Hi, I think that you should rather use the following code to import the model:
`tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], "./EXPER_DIR/superpoint_coco")`

**Comment by shylockyuan** [comment]
Sorry , I may not understand.
I tried to imitate example sentences which I found but it didn't work.
 
import tensorflow as tf

with tf.Session(graph=tf.Graph()) as sess:
  tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], "./EXPER_DIR/superpoint_coco")
  graph = tf.get_default_graph()

  img1 = cv2.imread('./5.ppm', cv2.IMREAD_GRAYSCALE)
  image1 = cv2.imread('./5.ppm', cv2.IMREAD_GRAYSCALE)
  interp = cv2.INTER_AREA
  img1 = cv2.resize(img1, (640, 480), interpolation=interp)
  img1 = (img1.astype('float32') / 255.)
  input = img1
  corners = sess.run(img1)

  keypoints = [cv2.KeyPoint(c[1], c[0], 1) for c in np.stack((np.array(corners[0]),np.array(corners[1])),axis=0).T]
  img=cv2.drawKeypoints(image1, keypoints, img1, color=(0, 255, 0))
  plt.imshow(img3), plt.show()

  File "pipei2.py", line 4, in <module>
    tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], "./EXPER_DIR/superpoint_coco")
  File "/home/wu/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 200, in load
    saved_model = _parse_saved_model(export_dir)
  File "/home/wu/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 78, in _parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: ./EXPER_DIR/superpoint_coco/{saved_model.pbtxt|saved_model.pb}

**Comment by rpautrat** [comment]
Well, you have to define this 'EXPER_DIR' string of course. You need to import first this: `from superpoint.settings import EXPER_PATH` and then use EXPER_PATH (and not EXPER_DIR) in your code to get the root location of your experiment.

You can find an example of a code loading the model and calling it on an image here: https://github.com/mmmfarrell/SuperPoint/blob/master/superpoint/match_features_demo.py
