### ISSUE TITLE
'magicLeap_mp_hp-v-repeat' and 'magicLeap_hp-v_desc'

### ISSUE THREAD

**Issue by yanhuanhuanyy** [rpautrat/SuperPoint#88]
Hi, @rpautrat  , thank you for sharing this repo.
when I run detector_repeatability_hpatches.ipynb and descriptors_evaluation_on_hpatches.ipynb, I have two questions.
Q1: How can I evaluate the 'magicLeap_mp_hp-v-repeat'(detector_repeatability_hpatches.ipynb)?
Q2: How can I evaluate the 'magicLeap_hp-v_desc'(descriptors_evaluation_on_hpatches.ipynb)?
The answer to the Q2 is in issue #24?  I tried it.  I added some lines in the file models/classical_detectors_descriptors.py. and  run the command: python export_descriptors.py configs/classical-descriptors.yaml superpoint_coco --export_name= magicLeap_hp-v_desc. But I meet a NameError: name 'SuperPointFrontend' is not defined,  Can you help me solve this problem?  How to use the pretrained MagicLeap Superpoint like any other classical baseline and do the evaluation on it?
Thanks for your answer about the Q1 and Q2.

**Comment by rpautrat** [comment]
Hi, sorry I forgot to answer.

To evaluate the pretrained model of Magic Leap, you can indeed add a few lines of code after the other classical baselines in the following files:

- Detector: in `superpoint/models/classical_detectors.py`:
```    elif config['method'] == 'pretrained_magic_point':
        weights_path = '<path_to_MagicLeap_repo>/SuperPointPretrainedNetwork/superpoint_v1.pth'
        fe = SuperPointFrontend(weights_path=weights_path,
                                nms_dist=config['nms'],
                                conf_thresh=0.015,
                                nn_thresh=0.7,
                                cuda=True)
        points, desc, detections = fe.run(im[:, :, 0] / 255.)
```

- Descriptors: in `superpoint/models/classical_detectors_descriptors.py`:
```elif config['method'] == 'pretrained_magic_point':
        weights_path = '<path_to_MagicLeap_repo>/SuperPointPretrainedNetwork/superpoint_v1.pth'
        fe = SuperPointFrontend(weights_path=weights_path,
                                nms_dist=config['nms'],
                                conf_thresh=0.015,
                                nn_thresh=0.7,
                                cuda=False)
        points, desc, detections = fe.run(im[:, :, 0] / 255.)
        points = points.astype(int)
        descriptors = np.zeros((im.shape[0], im.shape[1], 256), np.float)
        descriptors[points[1, :], points[0, :]] = np.transpose(desc)
```

Don't forget to add the line `from demo_superpoint import SuperPointNet, SuperPointFrontend` at the beginning of those two files (and install the demo_superpoint of Magic Leap as a Python package, their repo is available here: https://github.com/MagicLeapResearch/SuperPointPretrainedNetwork).

You can then evaluate both of them as you would do with the other classical baselines.

**Comment by yanhuanhuanyy** [comment]
It's okay. Thank you for your reply. I have solved the Q1 and Q2, My solution to the Q1 and Q2 is similar to what you said. But I have one more question, why Detector(classical_detectors.py) ' cuda= True' and Descriptors(classical_detectors_descriptors.py) 'cuda=False' ? Does cuda=true or false have a great influence on the experiment?

**Comment by rpautrat** [comment]
No, it shouldn't have an influence on the result, only on the running time. I don't remember why I set cuda=False for the descriptors, probably because I had an issue with cuda at the time.
But if cuda=True works for you, it is probably better to use it.

**Comment by yanhuanhuanyy** [comment]
I got it. Many thanks for your reply~
