### ISSUE TITLE
Discusion for Resize operation

### ISSUE THREAD

**Issue by roborocklsm** [rpautrat/SuperPoint#98]
It is not a ISSUE.

Superpoint inference speed could be around **20fps** (**~50ms/file**) on my PC (tf1.14+RTX2070). But while using the timeline tool I found that the **bicubic resize** operation would take around **20ms** (~50% of the whole inference progress) and it could be only be handled on CPUs.

I just wanna have a place to discuss this problem with someone else. If anyone has any idea, either modified the operation or the structure of the descriptor, I would be willing to hear.

**Comment by roborocklsm** [comment]
For me, my idea is to remove the resize operation and give padding to the descriptor convolution layers.

**Comment by rpautrat** [comment]
Wow, I didn't know that the bicubic interpolation was so slow here!

There is a quick improvement that can be made: replace the bicubic by bilinear interpolation. This is what the original authors did in their public implementation and they said that they didn't observe a significant change in performance. That should already speed up the process.

**Comment by roborocklsm** [comment]
I have done this several days ago, not a big improvement here.
![Screenshot from 2019-08-16 19-28-56](https://user-images.githubusercontent.com/53163084/63235562-8da26f00-c26c-11e9-95cf-551d3c7dd23a.png)

I am trying to avoid this operation. I would come back if I get something new.

**Comment by rpautrat** [comment]
I see, it is indeed still very slow...

I will also think about it and let you know if I find a nice way to overcome this.

**Comment by roborocklsm** [comment]
I accidentally found that **TF1.14** support bilinear resize GPU operation (but not for bicubic). Now it looks good.

**Comment by rpautrat** [comment]
Ah good! How does the profiling look like now? How fast is this GPU bilinear resize?

**Comment by roborocklsm** [comment]
![Screenshot from 2019-08-19 21-12-38](https://user-images.githubusercontent.com/53163084/63268203-30d3a280-c2c6-11e9-801a-94f0d83f1b5f.png)
It looks perfect now. The **Resize** op is only a small green square on the top, you can only see **Res**. And for this result, I only keep the "superpoint/descriptors" and "superpoint/prob" as output, other operations are removed.

Speed could go to ~80fps on my PC.

**Comment by rpautrat** [comment]
Really nice, thanks for this update!!

Yes, "superpoint/descriptors" and "superpoint/prob" are enough, the other outputs are mainly for debugging.
